# Generated by Django 5.2.17 on 2026-09-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=50, unique=True)),
                ('patient_token', models.CharField(max_length=50)),
                ('uhid', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=150)),
                ('timestamp', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Synced', 'Synced')], default='Pending', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
