import { ScreenId } from '../types';

export interface ScreenMetadata {
  id: ScreenId;
  screenNum: number;
  legacyId?: ScreenId;
  titleEn: string;
  titleHi: string;
  subtitleEn?: string;
  subtitleHi?: string;
  speechEn: string;
  speechHi: string;
  stepCurrent?: number;
  stepTotal?: number;
  stepTitleEn?: string;
  stepTitleHi?: string;
  hasCameraPip?: boolean;
}

export const SCREEN_CATALOG: Record<string, ScreenMetadata> = {
  s1: {
    id: 's1',
    screenNum: 1,
    legacyId: '00_IDLE',
    titleEn: 'Need to see the doctor?',
    titleHi: 'डॉक्टर से मिलना चाहते हैं?',
    subtitleEn: 'I can help you get ready for your visit.',
    subtitleHi: 'मैं आपकी डॉक्टर विज़िट की तैयारी में मदद करूँगा।',
    speechEn: 'Need to see the doctor? I can help you get ready for your visit. Step closer to begin.',
    speechHi: 'नमस्ते! डॉक्टर से मिलना चाहते हैं? मैं आपकी विज़िट तैयार करने में मदद करूँगा। स्क्रीन छुएं या स्टार्ट कहें।',
    hasCameraPip: false,
  },
  s2: {
    id: 's2',
    screenNum: 2,
    legacyId: '01_WELCOME',
    titleEn: 'Welcome to MediKiosk!',
    titleHi: 'MediKiosk में आपका स्वागत है!',
    subtitleEn: "I'll help you get ready for your doctor consultation.",
    subtitleHi: 'डॉक्टर से मिलने से पहले आइए आपकी कुछ ज़रूरी जानकारी और चेक-अप तैयार कर लें।',
    speechEn: "Welcome to MediKiosk! I'll help you get ready for your doctor consultation. Tap Start or say Start.",
    speechHi: 'MediKiosk में आपका स्वागत है! डॉक्टर कंसल्टेशन के लिए आइए तैयारी शुरू करें। स्टार्ट बटन दबाएं या स्टार्ट कहें।',
    hasCameraPip: false,
  },
  s3: {
    id: 's3',
    screenNum: 3,
    legacyId: '02_LANGUAGE',
    titleEn: 'Which language would you like to use?',
    titleHi: 'आप किस भाषा में बातचीत करना चाहेंगे?',
    subtitleEn: 'You can say the language or tap one below.',
    subtitleHi: 'अपनी पसंद की भाषा बोलें या नीचे दिए गए कार्ड पर टैप करें।',
    speechEn: 'Which language would you like to use? You can say Hindi or English.',
    speechHi: 'आप किस भाषा में बात करना चाहेंगे? आप हिंदी या इंग्लिश कह सकते हैं।',
    hasCameraPip: false,
  },
  s4: {
    id: 's4',
    screenNum: 4,
    legacyId: '03_CONSENT',
    titleEn: 'Digital Health Consent',
    titleHi: 'डिजिटल हेल्थ सहमति (Consent)',
    subtitleEn: "Before we begin, I'd like your permission to collect some information about your health and prepare it for your doctor.",
    subtitleHi: 'शुरू करने से पहले, आपकी स्वास्थ्य जानकारी एकत्रित करने और डॉक्टर के लिए तैयार करने हेतु आपकी सहमति चाहिए।',
    speechEn: "Before we begin, I'd like your permission to collect some information about your health and prepare it for your doctor. Say I agree or tap Continue.",
    speechHi: 'शुरू करने से पहले, डॉक्टर के लिए आपकी सेहत की जानकारी तैयार करने हेतु आपकी सहमति चाहिए। आगे बढ़ने के लिए "हाँ" कहें या जारी रखें दबाएं।',
    hasCameraPip: false,
  },
  s5: {
    id: 's5',
    screenNum: 5,
    legacyId: '04_EXISTING_NEW',
    titleEn: 'Are you an existing patient or a new patient?',
    titleHi: 'क्या आप पहले आ चुके हैं या पहली बार आए हैं?',
    subtitleEn: 'You can say it or tap an option below.',
    subtitleHi: 'आप बोलकर बता सकते हैं या नीचे विकल्प चुन सकते हैं।',
    speechEn: 'Are you an existing patient or a new patient? Say Existing or New.',
    speechHi: 'क्या आप पहले भी इस अस्पताल में आ चुके हैं या पहली बार आए हैं? बोलकर बताएं या विकल्प चुनें।',
    hasCameraPip: false,
  },
  s6: {
    id: 's6',
    screenNum: 6,
    legacyId: '05_NEW_PATIENT_RECORD',
    titleEn: 'Create your patient record?',
    titleHi: 'क्या आप अपना परमानेंट पेशेंट रिकॉर्ड बनाना चाहते हैं?',
    subtitleEn: 'Since this is your first time here, would you like me to create your patient record?',
    subtitleHi: 'क्योंकि आप पहली बार आए हैं, क्या आप भविष्य के लिए अपना रिकॉर्ड सेव करना चाहेंगे?',
    speechEn: 'Since this is your first time here, would you like me to create your patient record? Say Yes or Continue for this visit.',
    speechHi: 'चूंकि आप पहली बार आए हैं, क्या आप अपना पेशेंट रिकॉर्ड बनाना चाहते हैं? हाँ या केवल आज के लिए कहें।',
    hasCameraPip: false,
  },
  s7: {
    id: 's7',
    screenNum: 7,
    legacyId: '06A_IDENTIFY_EXISTING',
    titleEn: "Let's find your existing record",
    titleHi: 'आइए आपका पुराना रिकॉर्ड खोजें',
    subtitleEn: 'You can use Aadhaar, ABHA ID, or hospital UHID.',
    subtitleHi: 'आप आधार नंबर, आभा आईडी या यूएचआईडी का उपयोग कर सकते हैं।',
    speechEn: "Let's find your existing record. You can say Aadhaar, ABHA, or enter your number.",
    speechHi: 'आइए आपका पुराना रिकॉर्ड ढूंढें। आप आधार नंबर या अस्पताल की यूएचआईडी बता सकते हैं।',
    hasCameraPip: false,
  },
  s8: {
    id: 's8',
    screenNum: 8,
    legacyId: '06B_ENTER_PHONE',
    titleEn: 'Enter your ID number',
    titleHi: 'अपना पहचान नंबर दर्ज करें',
    subtitleEn: 'Enter your 12-digit Aadhaar or 14-digit ABHA number using the keypad.',
    subtitleHi: 'कीपैड की मदद से अपना 12 अंकों का आधार या आभा नंबर दर्ज करें।',
    speechEn: 'Please enter your ID number using the keypad or speak the digits clearly.',
    speechHi: 'कृपया कीपैड से अपना पहचान नंबर दर्ज करें या बोलकर बताएं।',
    hasCameraPip: false,
  },
  s9: {
    id: 's9',
    screenNum: 9,
    legacyId: '06C_SEARCHING',
    titleEn: 'Searching hospital registry...',
    titleHi: 'अस्पताल रिकॉर्ड में खोज रहे हैं...',
    subtitleEn: "This will only take a moment. We're matching your records.",
    subtitleHi: 'कृपया कुछ सेकंड प्रतीक्षा करें, आपकी जानकारी खोजी जा रही है।',
    speechEn: "Great! I'm now searching for your record. This will only take a moment.",
    speechHi: 'बहुत बढ़िया! मैं आपका पुराना रिकॉर्ड ढूंढ रहा हूँ, बस कुछ सेकंड लगेंगे।',
    hasCameraPip: false,
  },
  s10: {
    id: 's10',
    screenNum: 10,
    legacyId: '07_EXISTING_FOUND',
    titleEn: 'Is this you? Please confirm your profile',
    titleHi: 'क्या यह आप हैं? कृपया पुष्टि करें',
    subtitleEn: 'We found your previous hospital registration.',
    subtitleHi: 'हमें आपका पुराना रजिस्ट्रेशन रिकॉर्ड मिल गया है।',
    speechEn: 'Found your record! Is this you? Rohit Mehta, 38 years old. Say Yes or tap Confirm.',
    speechHi: 'आपका रिकॉर्ड मिल गया है! क्या आपका नाम रोहित मेहता है? पुष्टि के लिए हाँ कहें।',
    hasCameraPip: false,
  },
  s11: {
    id: 's11',
    screenNum: 11,
    legacyId: '08_IDENTIFICATION_FAILED',
    titleEn: "Couldn't find matching record",
    titleHi: 'रिकॉर्ड नहीं मिल सका',
    subtitleEn: "No worries, let's create a new patient profile for today's visit.",
    subtitleHi: 'कोई बात नहीं, आइए आज की विज़िट के लिए आपका नया प्रोफाइल बना लेते हैं।',
    speechEn: "I couldn't find a matching record. Let's create a new record for you.",
    speechHi: 'आपका पिछला रिकॉर्ड नहीं मिल पाया। कोई चिंता नहीं, आइए नया प्रोफाइल बना लेते हैं।',
    hasCameraPip: false,
  },
  s12: {
    id: 's12',
    screenNum: 12,
    legacyId: '09_NAME_INPUT',
    titleEn: 'What is your name?',
    titleHi: 'आपका नाम क्या है?',
    subtitleEn: 'You can say your full name aloud or type it below.',
    subtitleHi: 'अपना पूरा नाम बोलकर बताएं या नीचे टाइप करें।',
    speechEn: 'What is your name? You can say it aloud or enter it using the screen.',
    speechHi: 'आपका नाम क्या है? कृपया अपना पूरा नाम बोलें या स्क्रीन पर टाइप करें।',
    stepCurrent: 1,
    stepTotal: 6,
    stepTitleEn: 'Basic Information',
    stepTitleHi: 'सामान्य जानकारी',
    hasCameraPip: false,
  },
  s13: {
    id: 's13',
    screenNum: 13,
    legacyId: '10_AGE_INPUT',
    titleEn: 'How old are you?',
    titleHi: 'आपकी उम्र कितनी है?',
    subtitleEn: 'You can say your age or enter it using the number keypad.',
    subtitleHi: 'अपनी उम्र बोलकर बताएं या कीपैड से नंबर दर्ज करें।',
    speechEn: 'How old are you? You can say your age or use the number keypad.',
    speechHi: 'आपकी उम्र कितनी है? बोलकर बताएं या कीपैड से दर्ज करें।',
    stepCurrent: 2,
    stepTotal: 6,
    stepTitleEn: 'Basic Information',
    stepTitleHi: 'सामान्य जानकारी',
    hasCameraPip: false,
  },
  s14: {
    id: 's14',
    screenNum: 14,
    legacyId: '11_GENDER_INPUT',
    titleEn: 'What is your gender?',
    titleHi: 'आपका लिंग (Gender) क्या है?',
    subtitleEn: 'Please choose an option: Male, Female, Other, or Prefer not to say.',
    subtitleHi: 'कृपया विकल्प चुनें: पुरुष (Male), महिला (Female), या अन्य।',
    speechEn: 'What is your gender? Male, Female, or Other? Say your choice or tap below.',
    speechHi: 'आपका लिंग क्या है? पुरुष, महिला, या अन्य बोलें अथवा टैप करें।',
    stepCurrent: 3,
    stepTotal: 6,
    stepTitleEn: 'Basic Information',
    stepTitleHi: 'सामान्य जानकारी',
    hasCameraPip: false,
  },
  s15: {
    id: 's15',
    screenNum: 15,
    legacyId: '12_PHONE_INPUT',
    titleEn: 'What is your phone number?',
    titleHi: 'आपका मोबाइल नंबर क्या है?',
    subtitleEn: 'We use this to send your visit updates and token reminders.',
    subtitleHi: 'अपॉइंटमेंट और टोकन अपडेट के लिए अपना 10 अंकों का मोबाइल नंबर दर्ज करें।',
    speechEn: 'What is your phone number? You can say it aloud or enter it using the keypad.',
    speechHi: 'आपका मोबाइल नंबर क्या है? 10 अंकों का नंबर बोलें या कीपैड से दर्ज करें।',
    stepCurrent: 4,
    stepTotal: 6,
    stepTitleEn: 'Basic Information',
    stepTitleHi: 'सामान्य जानकारी',
    hasCameraPip: false,
  },
  s16: {
    id: 's16',
    screenNum: 16,
    legacyId: '13_PROFILE_CONFIRM',
    titleEn: 'Verify your phone with OTP',
    titleHi: 'ओटीपी (OTP) दर्ज करें',
    subtitleEn: 'We sent a 4-digit verification code to your mobile number.',
    subtitleHi: 'हमने आपके मोबाइल पर 4 अंकों का कोड भेजा है।',
    speechEn: 'We sent a 4-digit code to your phone. Please enter it on the keypad.',
    speechHi: 'आपके मोबाइल पर 4 अंकों का ओटीपी भेजा गया है, कृपया उसे दर्ज करें।',
    stepCurrent: 5,
    stepTotal: 6,
    stepTitleEn: 'Basic Information',
    stepTitleHi: 'सामान्य जानकारी',
    hasCameraPip: false,
  },
  s17: {
    id: 's17',
    screenNum: 17,
    legacyId: '13_PROFILE_CONFIRM',
    titleEn: 'Please confirm your profile details',
    titleHi: 'कृपया अपनी जानकारी की पुष्टि करें',
    subtitleEn: 'Check that your name, age, and phone number are correct.',
    subtitleHi: 'जाँच लें कि आपका नाम, उम्र और मोबाइल नंबर बिल्कुल सही हैं।',
    speechEn: 'Please check your basic details. If everything looks good, say Confirm or tap Next.',
    speechHi: 'कृपया अपनी जानकारी देख लें। सब सही है तो कन्फर्म कहें या आगे बढ़ें।',
    stepCurrent: 6,
    stepTotal: 6,
    stepTitleEn: 'Basic Information',
    stepTitleHi: 'सामान्य जानकारी',
    hasCameraPip: false,
  },
  s18: {
    id: 's18',
    screenNum: 18,
    legacyId: '14_PHOTO_CAPTURE',
    titleEn: "Let's take your photo!",
    titleHi: 'आइए आपकी फोटो ले लें!',
    subtitleEn: 'Position your face within the frame and stay still.',
    subtitleHi: 'चेहरे को कैमरे के सामने रखें और स्थिर रहें।',
    speechEn: "Let's take your photo! Position your face within the oval and stay still.",
    speechHi: 'आइए आपकी पहचान फोटो ले लें। अपना चेहरा कैमरे के सामने रखें और स्थिर रहें।',
    stepCurrent: 6,
    stepTotal: 6,
    stepTitleEn: 'Basic Information',
    stepTitleHi: 'सामान्य जानकारी',
    hasCameraPip: true,
  },
  s19: {
    id: 's19',
    screenNum: 19,
    legacyId: '15_CLINICAL_CONVERSATION',
    titleEn: 'What brings you to the hospital today?',
    titleHi: 'आज अस्पताल आने का मुख्य कारण क्या है?',
    subtitleEn: 'Please tell me your symptoms in your own words.',
    subtitleHi: 'अपनी परेशानी या लक्षण अपने शब्दों में सहजता से बताएं।',
    speechEn: 'To start with, can you tell me what brings you to the hospital today? You can say fever, cold, headache, or anything you feel.',
    speechHi: 'शुरुआत करने के लिए, बताइए आज आपको क्या तकलीफ़ है? जैसे सर्दी, बुखार, सिरदर्द या जो भी आप महसूस कर रहे हों।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s20: {
    id: 's20',
    screenNum: 20,
    legacyId: '16_LISTENING',
    titleEn: "I'm listening...",
    titleHi: 'मैं सुन रहा हूँ...',
    subtitleEn: 'Take your time. You can speak naturally.',
    subtitleHi: 'आराम से बोलिए। मैं आपकी बात ध्यान से सुन रहा हूँ।',
    speechEn: "I'm listening... Take your time. You can speak naturally.",
    speechHi: 'मैं सुन रहा हूँ... आराम से अपनी परेशानी बताएं।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s21: {
    id: 's21',
    screenNum: 21,
    legacyId: '17_PROCESSING',
    titleEn: 'Thinking about what you said...',
    titleHi: 'आपकी बात समझी जा रही है...',
    subtitleEn: "I'm using AI to understand your response and extract the important details.",
    subtitleHi: 'एआई द्वारा आपकी मुख्य शिकायतों को डॉक्टर के लिए संकलित किया जा रहा है।',
    speechEn: "Thanks! I'm now understanding your response... This may take a few seconds.",
    speechHi: 'धन्यवाद! आपकी बात का विश्लेषण किया जा रहा है, बस कुछ सेकंड का समय लगेगा।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s22: {
    id: 's22',
    screenNum: 22,
    legacyId: '18_I_HEARD_CONFIRM',
    titleEn: 'I heard that...',
    titleHi: 'मैंने यह समझा...',
    subtitleEn: 'Please confirm if this is correct. You can also tell me if you want to change anything.',
    subtitleHi: 'कृपया पुष्टि करें कि क्या यह सही है या कुछ बदलना चाहते हैं।',
    speechEn: "Here's what I heard... Please check if this is correct. Say Yes or tap Continue.",
    speechHi: 'मैंने यह समझा है। कृपया देख लें कि क्या यह सही है। सही है तो "हाँ" कहें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s23: {
    id: 's23',
    screenNum: 23,
    legacyId: '20_CHOICE_QUESTION',
    titleEn: 'How long have you had this?',
    titleHi: 'यह परेशानी कितने समय से है?',
    subtitleEn: 'Please tell me how many days or weeks you have felt this way.',
    subtitleHi: 'कृपया बताएं कि यह लक्षण कितने दिनों या हफ़्तों से है।',
    speechEn: 'How long have you had these symptoms? For example, since today, 2 days, or a week?',
    speechHi: 'यह समस्या आपको कब से है? जैसे आज से, दो दिन से, या एक हफ्ते से?',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s24: {
    id: 's24',
    screenNum: 24,
    legacyId: '20_CHOICE_QUESTION',
    titleEn: 'Do you currently have a cough?',
    titleHi: 'क्या आपको खांसी या सांस में कोई दिक्कत है?',
    subtitleEn: 'Please say Yes or No, or choose from the options below.',
    subtitleHi: 'हाँ या नहीं कहें, या नीचे दिए गए विकल्पों में से चुनें।',
    speechEn: 'Do you currently have a cough or chest discomfort? Say Yes or No.',
    speechHi: 'क्या आपको अभी खांसी या सीने में भारीपन है? हाँ या नहीं कहें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s25: {
    id: 's25',
    screenNum: 25,
    legacyId: '21_RETRY_UNCLEAR',
    titleEn: "I didn't quite catch that",
    titleHi: 'माफ कीजिए, मैं ठीक से समझ नहीं पाया',
    subtitleEn: 'Could you please repeat your answer or tap one of the options below?',
    subtitleHi: 'कृपया अपनी बात दोबारा दोहराएं या नीचे दिए गए विकल्पों पर टैप करें।',
    speechEn: "I didn't quite catch that. Could you please repeat your answer or tap an option below?",
    speechHi: 'माफ कीजिए, मैं सुन नहीं पाया। क्या आप दोबारा दोहरा सकते हैं या स्क्रीन पर टैप कर सकते हैं?',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s26: {
    id: 's26',
    screenNum: 26,
    legacyId: '22_UNKNOWN_NOT_SURE',
    titleEn: 'Which option applies to you?',
    titleHi: 'इनमें से कौन सा विकल्प आपके लिए सही है?',
    subtitleEn: "It's okay if you're not sure or if this doesn't apply to you.",
    subtitleHi: 'यदि आप निश्चित नहीं हैं तो कोई बात नहीं, उपयुक्त विकल्प चुनें।',
    speechEn: "No worries! It's okay if you're not sure. Choose the option that fits best.",
    speechHi: 'कोई बात नहीं! अगर आपको ठीक से याद नहीं है तो जो विकल्प सबसे सही लगे उसे चुनें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s27: {
    id: 's27',
    screenNum: 27,
    legacyId: '23_RED_FLAG',
    titleEn: 'This may be a serious symptom',
    titleHi: 'यह एक गंभीर लक्षण हो सकता है (Red Flag)',
    subtitleEn: "It's important to get the right care as soon as possible. Please inform the medical staff immediately.",
    subtitleHi: 'तुरंत डॉक्टरी देखभाल आवश्यक है। कृपया अस्पताल स्टाफ को तत्काल सूचित करें।',
    speechEn: 'Your symptoms may need prompt attention. Please inform hospital staff immediately or call 108 in an emergency.',
    speechHi: 'आपके लक्षण गंभीर हो सकते हैं। कृपया तुरंत अस्पताल स्टाफ को बताएं या इमरजेंसी नंबर 108 पर संपर्क करें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s28: {
    id: 's28',
    screenNum: 28,
    legacyId: '24_MEASUREMENTS_INTRO',
    titleEn: "We'll now take a few measurements",
    titleHi: 'आइए अब कुछ सामान्य जांच (Vitals) कर लें',
    subtitleEn: 'These are simple, quick and painless: Blood Pressure, Oxygen Saturation, Heart Rate.',
    subtitleHi: 'यह पूरी तरह सुरक्षित और दर्दरहित हैं: ब्लड प्रेशर, पल्स और ऑक्सीजन सैचुरेशन।',
    speechEn: "Now let's take some quick measurements. These help us understand your health better. Say Start or tap Begin.",
    speechHi: 'आइए अब कुछ सामान्य जांच जैसे ब्लड प्रेशर और ऑक्सीजन नाप लेते हैं। शुरू करने के लिए "तैयार" कहें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s29: {
    id: 's29',
    screenNum: 29,
    legacyId: '25_BP_INSTRUCTIONS',
    titleEn: 'Blood Pressure Measurement',
    titleHi: 'रक्तचाप (Blood Pressure) जांच निर्देश',
    subtitleEn: 'Sit comfortably, place the cuff on your arm, keep still, and avoid talking.',
    subtitleHi: 'आराम से बैठें, कफ को बांह पर लगाएं, शांत रहें और बातचीत न करें।',
    speechEn: "Let's measure your blood pressure. Sit comfortably, place the cuff, and keep your arm at heart level.",
    speechHi: 'आइए ब्लड प्रेशर नापें। आराम से बैठें, कफ लगाएं और अपनी बांह को दिल के स्तर पर रखें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s30: {
    id: 's30',
    screenNum: 30,
    legacyId: '26_BP_POSITIONING',
    titleEn: 'Position Your Arm',
    titleHi: 'अपनी बांह की सही स्थिति बनाएं',
    subtitleEn: 'Please adjust your position as shown. Keep your arm rested on the table.',
    subtitleHi: 'दिखाए गए अनुसार अपनी बांह को मेज़ पर रखें और हथेली ऊपर की ओर रखें।',
    speechEn: "Great! Make sure your arm is at heart level and hand is relaxed. Say Ready when you are set.",
    speechHi: 'बहुत अच्छा! सुनिश्चित करें कि आपकी बांह मेज़ पर स्थिर है। तैयार होने पर "तैयार" कहें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s31: {
    id: 's31',
    screenNum: 31,
    legacyId: '27_BP_MEASURING',
    titleEn: 'Measuring Your Blood Pressure',
    titleHi: 'ब्लड प्रेशर नापा जा रहा है...',
    subtitleEn: 'Please stay still and relax. This will take about 30 seconds.',
    subtitleHi: 'कृपया 30 सेकंड तक शांत रहें, हिलें-डुलें नहीं।',
    speechEn: 'Measuring your blood pressure... Please stay still and avoid moving or speaking.',
    speechHi: 'रक्तचाप नापा जा रहा है... कृपया कुछ क्षण शांत और स्थिर बैठें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s32: {
    id: 's32',
    screenNum: 32,
    legacyId: '28_BP_RESULT',
    titleEn: 'Your Blood Pressure Result',
    titleHi: 'आपके ब्लड प्रेशर का परिणाम',
    subtitleEn: '118/78 mmHg · Normal blood pressure range.',
    subtitleHi: '118/78 mmHg · सामान्य रक्तचाप सीमा।',
    speechEn: "Great! We've got your blood pressure reading: 118 over 78, perfectly normal.",
    speechHi: 'बहुत अच्छा! आपका ब्लड प्रेशर 118 और 78 आया है, जो बिल्कुल सामान्य है।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s33: {
    id: 's33',
    screenNum: 33,
    legacyId: '29_SPO2_MEASUREMENT',
    titleEn: 'Oxygen Saturation (SpO2) & Pulse',
    titleHi: 'ऑक्सीजन स्तर (SpO2) एवं नाड़ी की गति',
    subtitleEn: 'SpO2: 98% · Pulse: 74 bpm. Normal oxygen levels.',
    subtitleHi: 'ऑक्सीजन 98% और पल्स 74 प्रति मिनट, बिल्कुल सामान्य स्तर।',
    speechEn: "Oxygen saturation is 98 percent and pulse is 74. Everything looks healthy.",
    speechHi: 'ऑक्सीजन स्तर 98 प्रतिशत और नाड़ी की गति 74 है, सब कुछ स्वस्थ है।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s34: {
    id: 's34',
    screenNum: 34,
    legacyId: '30_DOCUMENT_INTRO',
    titleEn: 'Scan Your Medical Documents',
    titleHi: 'अपने पुराने मेडिकल दस्तावेज़ या पर्चे स्कैन करें',
    subtitleEn: 'You can scan previous prescriptions, lab reports, or discharge summaries.',
    subtitleHi: 'आप पुराने डॉक्टर के पर्चे, खून की जांच रिपोर्ट या अस्पताल की पर्ची स्कैन कर सकते हैं।',
    speechEn: "Next, let's scan your medical documents. Do you have any previous prescriptions or lab reports? Say Yes to scan or No to skip.",
    speechHi: 'क्या आपके पास कोई पुराना डॉक्टर का पर्चा या रिपोर्ट है? स्कैन करने के लिए "हाँ" कहें या आगे बढ़ने के लिए "नहीं" कहें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s35: {
    id: 's35',
    screenNum: 35,
    legacyId: '31_PLACE_DOCUMENT',
    titleEn: 'Insert Your Document',
    titleHi: 'दस्तावेज़ स्कैनर स्लॉट में रखें',
    subtitleEn: 'Feed your document into the scanner slot below the screen as shown.',
    subtitleHi: 'स्क्रीन के नीचे बने स्कैनर स्लॉट में अपना पर्चा सीधा डालें।',
    speechEn: 'Please insert your document face up into the scanner slot below the screen.',
    speechHi: 'कृपया अपना दस्तावेज़ स्क्रीन के नीचे दिए गए स्कैनर स्लॉट में सीधा रखें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s36: {
    id: 's36',
    screenNum: 36,
    legacyId: '32_SCANNING_BACKGROUND',
    titleEn: 'Scanning Document...',
    titleHi: 'दस्तावेज़ स्कैन हो रहा है...',
    subtitleEn: 'Your document is being captured. This will only take a few seconds.',
    subtitleHi: 'दस्तावेज़ की डिजिटल प्रति तैयार हो रही है, कृपया थोड़ा इंतजार करें।',
    speechEn: "Scanning your document... Please wait while we capture and process the image.",
    speechHi: 'आपका दस्तावेज़ स्कैन हो रहा है, कृपया कुछ सेकंड प्रतीक्षा करें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s37: {
    id: 's37',
    screenNum: 37,
    legacyId: '32_SCANNING_BACKGROUND',
    titleEn: 'Scanning in background...',
    titleHi: 'बैकग्राउंड में स्कैन जारी है...',
    subtitleEn: "I've started scanning your document in the background. You can continue.",
    subtitleHi: 'स्कैन बैकग्राउंड में चल रहा है, आप आगे की प्रक्रिया जारी रख सकते हैं।',
    speechEn: "I've started scanning your document in the background. You can continue.",
    speechHi: 'दस्तावेज़ बैकग्राउंड में प्रोसेस हो रहा है, आइए हम आगे बढ़ें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s38: {
    id: 's38',
    screenNum: 38,
    legacyId: '33_DOCUMENT_SCANNED',
    titleEn: 'Document Scanned 100%',
    titleHi: 'दस्तावेज़ सफलतापूर्वक स्कैन हो गया (100%)',
    subtitleEn: "Your document has been scanned successfully. We'll extract the details.",
    subtitleHi: 'दस्तावेज़ सफलतापूर्वक स्कैन हो गया है।',
    speechEn: 'Great! Your document has been scanned successfully.',
    speechHi: 'बहुत बढ़िया! आपका दस्तावेज़ सफलतापूर्वक स्कैन हो गया है।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s39: {
    id: 's39',
    screenNum: 39,
    legacyId: '34_OCR_PROCESSING',
    titleEn: "I'm now reading your document...",
    titleHi: 'दस्तावेज़ से जानकारी पढ़ी जा रही है...',
    subtitleEn: "Extracting key clinical information using Gemini Multimodal OCR.",
    subtitleHi: 'एआई द्वारा पर्चे में लिखी दवाइयों और टेस्ट रिपोर्ट को पढ़ा जा रहा है।',
    speechEn: "I'm now reading your document and extracting the important medical information.",
    speechHi: 'मैं आपके पर्चे में लिखी जानकारी और दवाइयों को समझ रहा हूँ।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s40: {
    id: 's40',
    screenNum: 40,
    legacyId: '36_DOCUMENT_COMPLETE',
    titleEn: 'Information Extracted Successfully',
    titleHi: 'जानकारी सफलतापूर्वक संकलित हो गई',
    subtitleEn: 'Prescription details, medications, and clinical impressions saved for doctor.',
    subtitleHi: 'दवाइयों और डॉक्टर के निर्देशों का विवरण सुरक्षित कर लिया गया है।',
    speechEn: "I've successfully extracted the key information from your document. All set!",
    speechHi: 'आपके पर्चे की मुख्य जानकारी और दवाइयां सफलतापूर्वक दर्ज हो गई हैं।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s41: {
    id: 's41',
    screenNum: 41,
    legacyId: '35_DOCUMENT_PROBLEM',
    titleEn: 'Scan Unsuccessful - Image Unclear',
    titleHi: 'स्कैन साफ नहीं आ सका',
    subtitleEn: "Looks like we couldn't read this document clearly. Let's try scanning again.",
    subtitleHi: 'दस्तावेज़ की तस्वीर साफ नहीं दिख रही है। आइए इसे दोबारा स्कैन करें।',
    speechEn: "Looks like we couldn't read this document clearly. Let's try scanning it again.",
    speechHi: 'लगता है पर्चा थोड़ा धुंधला था। कृपया इसे सीधा रखकर दोबारा स्कैन करें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s42: {
    id: 's42',
    screenNum: 42,
    legacyId: '35_DOCUMENT_PROBLEM',
    titleEn: 'Scan Again or Skip for Now?',
    titleHi: 'दोबारा स्कैन करें या अभी छोड़ें?',
    subtitleEn: 'Would you like to try scanning again, or continue to your appointment?',
    subtitleHi: 'क्या आप दोबारा स्कैन करना चाहते हैं या सीधे आगे बढ़ना चाहते हैं?',
    speechEn: 'Would you like to try scanning again, or skip this step for now?',
    speechHi: 'क्या आप दोबारा स्कैन करना चाहेंगे या इसे छोड़कर आगे बढ़ना चाहेंगे?',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s43: {
    id: 's43',
    screenNum: 43,
    legacyId: '36_DOCUMENT_COMPLETE',
    titleEn: 'All Documents Collected!',
    titleHi: 'सभी दस्तावेज़ एकत्रित हो गए!',
    subtitleEn: 'We have everything needed for Dr. Anjali Verma.',
    subtitleHi: 'डॉक्टर के लिए आपकी सभी आवश्यक जानकारी तैयार है।',
    speechEn: "All your documents are collected! We have everything we need. Let's continue.",
    speechHi: 'आपके सभी दस्तावेज़ जमा हो गए हैं। आइए अब आपकी केस समरी तैयार करें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Tell Us About Your Health',
    stepTitleHi: 'अपनी सेहत के बारे में बताएं',
    hasCameraPip: true,
  },
  s44: {
    id: 's44',
    screenNum: 44,
    legacyId: '37_PREPARING_CASE',
    titleEn: 'Preparing your case...',
    titleHi: 'आपका केस तैयार किया जा रहा है...',
    subtitleEn: 'Combining your conversation, vitals, and medical documents.',
    subtitleHi: 'आपकी बातचीत, वाइटल्स और दस्तावेज़ों को मिलाकर डॉक्टर फाइल तैयार हो रही है।',
    speechEn: "Preparing your case... Putting together all your information for your doctor.",
    speechHi: 'आपका मेडिकल केस तैयार हो रहा है, ताकि डॉक्टर को आपकी पूरी जानकारी एक जगह मिल सके।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Preparing Your Case',
    stepTitleHi: 'केस तैयार किया जा रहा है',
    hasCameraPip: true,
  },
  s45: {
    id: 's45',
    screenNum: 45,
    legacyId: '38_CASE_READY',
    titleEn: 'Your case is ready!',
    titleHi: 'आपका केस तैयार है!',
    subtitleEn: 'Your doctor will now have a complete picture to provide better care.',
    subtitleHi: 'आपकी पूरी समरी डॉक्टर अंजलि वर्मा के वर्कस्टेशन पर भेज दी गई है।',
    speechEn: 'Your case is ready! Your doctor will now have a complete picture.',
    speechHi: 'आपका केस तैयार हो गया है! अब डॉक्टर को आपकी पूरी जानकारी उपलब्ध होगी।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Preparing Your Case',
    stepTitleHi: 'केस तैयार किया जा रहा है',
    hasCameraPip: false,
  },
  s46: {
    id: 's46',
    screenNum: 46,
    legacyId: '42_ALL_SET',
    titleEn: "Great! You're all set",
    titleHi: 'बहुत बढ़िया! आपकी चेक-इन पूरी हो गई',
    subtitleEn: 'We have collected everything we need for your visit.',
    subtitleHi: 'आपकी विज़िट के लिए आवश्यक सभी जानकारी एकत्र कर ली गई है।',
    speechEn: "Great! You're all set. We've collected everything we need for your visit.",
    speechHi: 'बहुत बढ़िया! आपकी चेक-इन पूरी हो चुकी है। आइए आपका टोकन और कलाई का पट्टा ले लें।',
    stepCurrent: 7,
    stepTotal: 7,
    stepTitleEn: 'Preparing Your Case',
    stepTitleHi: 'केस तैयार किया जा रहा है',
    hasCameraPip: false,
  },
  s47: {
    id: 's47',
    screenNum: 47,
    legacyId: '39_VISIT_QR',
    titleEn: 'Your Visit QR Has Been Created!',
    titleHi: 'आपका विज़िट क्यूआर कोड तैयार है!',
    subtitleEn: 'Your doctor can scan this code to securely access your prepared case.',
    subtitleHi: 'डॉक्टर इस कोड को स्कैन करके आपकी पूरी मेडिकल समरी देख सकते हैं।',
    speechEn: 'Your visit QR has been created! Keep this token number or scan it at Counter 4.',
    speechHi: 'आपका विज़िट क्यूआर कोड बन गया है! टोकन नंबर A1054 याद रखें या काउंटर 4 पर दिखाएं।',
    hasCameraPip: false,
  },
  s48: {
    id: 's48',
    screenNum: 48,
    legacyId: '40_WRISTBAND_PRINTING',
    titleEn: 'Get Your Wristband Ready',
    titleHi: 'कलाई का पट्टा (Wristband) प्राप्त करने के लिए तैयार रहें',
    subtitleEn: 'Your thermal wristband with QR code is printing automatically.',
    subtitleHi: 'क्यूआर कोड युक्त कलाई का पट्टा प्रिंट हो रहा है।',
    speechEn: 'Get your wristband ready. Place your hand under the dispenser slot.',
    speechHi: 'प्रिंटर स्लॉट के नीचे अपना हाथ रखें, आपका कलाई का पट्टा निकल रहा है।',
    hasCameraPip: false,
  },
  s49: {
    id: 's49',
    screenNum: 49,
    legacyId: '41_COLLECT_WRISTBAND',
    titleEn: 'Dispensing your wristband...',
    titleHi: 'कलाई का पट्टा बाहर आ रहा है...',
    subtitleEn: 'Please keep your hand steady and take the wristband once it is fully out.',
    subtitleHi: 'पट्टा पूरी तरह बाहर आने पर इसे आराम से निकाल लें और कलाई पर बांध लें।',
    speechEn: 'Almost there! Your wristband is being dispensed. Please take it once it is fully out.',
    speechHi: 'आपका कलाई का पट्टा तैयार है। कृपया इसे निकाल लें।',
    hasCameraPip: false,
  },
  s50: {
    id: 's50',
    screenNum: 50,
    legacyId: '42_ALL_SET',
    titleEn: "You're All Set! Consultation Room 4",
    titleHi: 'आप तैयार हैं! कमरा नंबर 4 (डॉ. अंजलि वर्मा)',
    subtitleEn: 'Please proceed to General Medicine OPD · Counter 4. Estimated wait: 4 mins.',
    subtitleHi: 'कृपया जनरल मेडिसिन ओपीडी, काउंटर 4 पर जाएं। अनुमानित प्रतीक्षा समय: 4 मिनट।',
    speechEn: "You're all set! Please proceed to Consultation Room 4 for Dr. Anjali Verma.",
    speechHi: 'आपकी विज़िट रजिस्टर हो गई है! कृपया कमरा नंबर 4 में डॉक्टर अंजलि वर्मा के पास जाएं।',
    hasCameraPip: false,
  },
  s51: {
    id: 's51',
    screenNum: 51,
    legacyId: '43_SESSION_COMPLETE',
    titleEn: 'Thank You!',
    titleHi: 'धन्यवाद!',
    subtitleEn: 'Your check-in is complete. Wishing you a safe and healthy visit!',
    subtitleHi: 'आपकी चेक-इन पूरी हो गई है। हम आपके शीघ्र स्वस्थ होने की कामना करते हैं!',
    speechEn: 'Thank you for using MediKiosk! Wishing you a safe and healthy visit.',
    speechHi: 'MediKiosk का उपयोग करने के लिए धन्यवाद! हम आपके अच्छे स्वास्थ्य की कामना करते हैं।',
    hasCameraPip: false,
  },
};

export function getScreenNum(screenId: ScreenId): number {
  if (typeof screenId === 'string' && screenId.startsWith('s') && !isNaN(Number(screenId.slice(1)))) {
    return Number(screenId.slice(1));
  }
  // Lookup by legacy id
  const entry = Object.values(SCREEN_CATALOG).find(s => s.legacyId === screenId);
  return entry ? entry.screenNum : 1;
}

export function getScreenMeta(screenId: ScreenId): ScreenMetadata {
  const num = getScreenNum(screenId);
  return SCREEN_CATALOG[`s${num}`] || SCREEN_CATALOG.s1;
}

export const ALL_51_SCREENS: ScreenMetadata[] = Object.values(SCREEN_CATALOG).sort(
  (a, b) => a.screenNum - b.screenNum
);

