# Generated by Django 5.2.17 on 2026-09-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_hpr', models.CharField(default='HPR123456', max_length=50, unique=True)),
                ('show_ayush_default', models.BooleanField(default=True)),
                ('pinned_specialists', models.JSONField(default=list)),
                ('auto_open_docs', models.BooleanField(default=True)),
                ('highlight_abnormal_vitals', models.BooleanField(default=True)),
                ('confirm_before_push', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(default='General Medicine', max_length=100)),
                ('content', models.TextField()),
                ('shortcut', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
