from django.core.management.base import BaseCommand
from apps.authentication.models import DoctorProfile, Workspace
from apps.settings_service.models import DoctorSettings, NoteTemplate
from apps.sync_service.models import SyncActionItem
from apps.patients.models import (
    Patient,
    Vitals,
    ClinicalSummary,
    RedFlag,
    ScannedDocument,
    QueueItem,
)
from apps.consultations.models import AuditLog

class Command(BaseCommand):
    help = 'Seeds database with realistic MediKiosk OPD demo patients, doctor profile, and settings.'

    def handle(self, *args, **options):
        self.stdout.write("Starting MediKiosk Doctor Interface database seeding...")

        # 1. Doctor Profile
        doctor, _ = DoctorProfile.objects.update_or_create(
            hpr_id='HPR123456',
            defaults={
                'name': 'Dr. Anjali Verma',
                'degrees': 'MBBS, MD (Internal Medicine)',
                'designation': 'Consultant – General Medicine',
                'department': 'General Medicine OPD',
                'hospital': 'District Hospital, Bhopal',
                'hospital_address': 'E-102, Arera Colony, Bhopal, Madhya Pradesh - 462016',
                'counter_desk': 'Desk 4',
                'timings': '09:00 AM – 04:00 PM',
                'email': 'anjali.verma@bhopalhosp.gov.in',
                'phone': '+91 98765 43210',
                'is_verified_abdm': True,
                'status': 'Active',
            }
        )

        # 2. Workspaces
        workspaces = [
            {'department': 'General Medicine OPD', 'desk': 'Desk 4', 'hospital': 'District Hospital, Bhopal'},
            {'department': 'General Medicine OPD', 'desk': 'Desk 2', 'hospital': 'District Hospital, Bhopal'},
            {'department': 'Cardiology OPD', 'desk': 'Desk 1', 'hospital': 'District Hospital, Bhopal'},
            {'department': 'AYUSH / Panchakarma OPD', 'desk': 'Desk 3', 'hospital': 'District Hospital, Bhopal'},
        ]
        for ws in workspaces:
            Workspace.objects.get_or_create(department=ws['department'], desk=ws['desk'], defaults=ws)

        # 3. Settings & Note Templates
        DoctorSettings.objects.update_or_create(
            doctor_hpr='HPR123456',
            defaults={
                'show_ayush_default': True,
                'pinned_specialists': ['Cardiology', 'Neurology', 'Orthopedics', 'Endocrinology'],
                'auto_open_docs': True,
                'highlight_abnormal_vitals': True,
                'confirm_before_push': True,
            }
        )

        templates = [
            {
                'template_id': 'tpl-1',
                'title': 'General Follow-up Note',
                'category': 'General Medicine',
                'shortcut': '/gen',
                'content': 'Patient presents for routine follow-up. Vital signs are within normal limits. Reports general adherence to prescribed regimen. No new complaints or red flag symptoms reported.',
                'order': 1,
            },
            {
                'template_id': 'tpl-2',
                'title': 'Hypertension Review',
                'category': 'Cardiology',
                'shortcut': '/htn',
                'content': 'Known case of Essential Hypertension on maintenance therapy. Current BP monitored and evaluated. Review of end-organ symptoms negative. Advised sodium restriction, hydration, and periodic ambulatory BP logs.',
                'order': 2,
            },
            {
                'template_id': 'tpl-3',
                'title': 'Diabetes Follow-up',
                'category': 'Endocrinology',
                'shortcut': '/dm',
                'content': 'Type 2 Diabetes Mellitus review. Fasting blood sugar checked. No symptoms of hypoglycemia or peripheral neuropathy. Dietary advice reiterated, advised HbA1c screening.',
                'order': 3,
            },
            {
                'template_id': 'tpl-4',
                'title': 'Post-operative Review',
                'category': 'Surgery',
                'shortcut': '/postop',
                'content': 'Surgical site inspected: clean, dry, healing by primary intention. No discharge or erythema. Sutures intact. Patient ambulating well. Analgesics tapered.',
                'order': 4,
            },
        ]
        for t in templates:
            NoteTemplate.objects.update_or_create(template_id=t['template_id'], defaults=t)

        # 4. Clear existing patients for fresh seed
        Patient.objects.all().delete()

        # 5. Define All 12 Mock Patients (A1041 to A1052)
        patients_data = [
            {
                "token": "A1052",
                "uhid": "UHID778901",
                "abha": "ABHA832017665432",
                "name": "Rohit Mehta",
                "age": 36,
                "gender": "Male",
                "phone": "+91 98765 43210",
                "address": "E-102, Arera Colony, Bhopal, Madhya Pradesh - 462016",
                "attendant": "Self",
                "emergency_name": "Neha Mehta",
                "emergency_relation": "Spouse",
                "emergency_phone": "+91 98765 43211",
                "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
                "queue_num": 1,
                "wait_time": "Just now",
                "arrived_at": "09:12 AM",
                "status": "New",
                "chief_complaint": "Chest pain since yesterday.",
                "hpi": "Patient reports intermittent left-sided chest pain since yesterday evening. Pain is moderate in intensity, non-radiating, and not associated with exertion. Also reports mild shortness of breath and fatigue. No similar episodes in the past.",
                "past": ["Hypertension (diagnosed 2 years ago)", "No history of diabetes", "No previous surgeries", "No hospitalizations in last 5 years"],
                "allergy": "Penicillin",
                "reaction": "Rash",
                "current_meds": ["Amlodipine 5 mg (OD)"],
                "family": ["Father: Hypertension", "Mother: Type 2 Diabetes", "No family history of heart disease in family"],
                "personal": ["Non-smoker", "Occasional alcohol consumption", "Sedentary lifestyle (desk job)"],
                "ros": {"respiratory": "Mild breathlessness", "cardiovascular": "Chest pain", "gastrointestinal": "No nausea or vomiting", "others": "No significant complaints"},
                "investigations": ["ECG on file (03 Sep 2026) – see attached", "Blood Panel available (28 Aug 2026)", "No other investigations reported"],
                "vitals": {
                    "bp_value": "148/92 mmHg", "bp_source": "kiosk_device", "bp_timestamp": "Kiosk · 09:12 AM", "bp_is_abnormal": True,
                    "sugar_value": "108 mg/dL", "sugar_source": "self_reported", "sugar_timestamp": "Self reported · 09:10 AM",
                    "blood_group_value": "B+", "blood_group_source": "self_reported",
                    "spo2_value": "97 %", "spo2_source": "kiosk_device", "spo2_timestamp": "Kiosk · 09:12 AM",
                    "pulse_value": "84 bpm", "pulse_source": "kiosk_device", "pulse_timestamp": "Kiosk · 09:12 AM",
                    "temp_value": "98.4 °F", "temp_source": "kiosk_device", "temp_timestamp": "Kiosk · 09:12 AM",
                    "weight_value": "67 kg", "weight_source": "kiosk_device", "weight_timestamp": "Kiosk · 09:12 AM",
                },
                "red_flags": [
                    {"symptom": "Chest pain reported since yesterday. Monitor and assess immediately.", "severity": "Needs attention", "badge_label": "Chest Pain", "badge_type": "red"}
                ],
                "ayush": {"prakriti": "Vata-Pitta", "vikriti": "Vata aggravation", "agni": "Madhyama", "koshtha": "Madhyama"},
                "documents": [
                    {
                        "doc_id": "ecg-rohit", "doc_type": "ECG", "subtitle": "12-Lead Electrocardiogram", "pages": 2, "date": "03 Sep 2026", "time": "09:08 AM",
                        "file_id": "DOC_20260903_090812", "source": "MediKiosk (Patient Scan)",
                        "impression": "Normal sinus rhythm. No acute ST-T changes seen. Please correlate clinically.",
                        "signatory": "Dr. S. Kulkarni MD (Cardiology) Reg. No. MP/23456",
                        "preview_url": "/ecg_p1.svg",
                        "pages_list": [
                            {"pageNumber": 1, "title": "12-Lead Rhythm Strip Lead I, II, III, aVR, aVL, aVF", "imageUrl": "/ecg_p1.svg"},
                            {"pageNumber": 2, "title": "Precordial Leads V1 - V6 Detailed Analysis", "imageUrl": "/ecg_p2.svg"},
                        ]
                    },
                    {
                        "doc_id": "blood-rohit", "doc_type": "Blood Panel", "subtitle": "Complete Blood Count & Lipid Profile", "pages": 3, "date": "28 Aug 2026", "time": "02:15 PM",
                        "file_id": "DOC_20260828_141500", "source": "MediKiosk (Patient Scan)",
                        "impression": "Mild dyslipidemia. Total Cholesterol 218 mg/dL. Hemoglobin 14.2 g/dL.",
                        "signatory": "City Care Diagnostics Reg. No. LAB/9871",
                        "preview_url": "/blood_panel_p1.svg",
                        "pages_list": [
                            {"pageNumber": 1, "title": "Complete Blood Count (CBC) with Differential", "imageUrl": "/blood_panel_p1.svg"},
                            {"pageNumber": 2, "title": "Lipid Profile & Liver Function Tests", "imageUrl": "/blood_panel_p1.svg"},
                            {"pageNumber": 3, "title": "Kidney Function & Electrolytes", "imageUrl": "/blood_panel_p1.svg"},
                        ]
                    },
                    {
                        "doc_id": "rx-rohit", "doc_type": "Previous Prescription", "subtitle": "Hypertension Maintenance Rx", "pages": 1, "date": "15 Aug 2026", "time": "11:20 AM",
                        "file_id": "DOC_20260815_112045", "source": "MediKiosk (Patient Scan)",
                        "impression": "Tab. Amlodipine 5mg OD x 30 days. Regular BP check advised.",
                        "signatory": "Dr. R. K. Sharma MD (General Medicine)",
                        "preview_url": "/blood_panel_p1.svg",
                        "pages_list": [
                            {"pageNumber": 1, "title": "Outpatient Prescription Slip", "imageUrl": "/blood_panel_p1.svg"},
                        ]
                    }
                ]
            },
            {
                "token": "A1047",
                "uhid": "UHID221904",
                "abha": "ABHA190283746152",
                "name": "Pooja Singh",
                "age": 19,
                "gender": "Female",
                "phone": "+91 98765 43212",
                "address": "B-44, Shahpura, Bhopal",
                "attendant": "Mother",
                "emergency_name": "Sunita Singh",
                "emergency_relation": "Mother",
                "emergency_phone": "+91 98765 43213",
                "photo": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
                "queue_num": 6,
                "wait_time": "42 min",
                "arrived_at": "08:32 AM",
                "status": "Reviewed",
                "chief_complaint": "Severe headache and vomiting.",
                "hpi": "High fever since 3 days (recorded 39.2°C at kiosk) associated with severe frontal throbbing headache, neck stiffness, and multiple episodes of vomiting.",
                "past": ["No prior hospitalizations", "No chronic illnesses"],
                "allergy": "Sulfa drugs",
                "reaction": "Urticaria",
                "current_meds": ["Paracetamol 650 mg SOS"],
                "family": ["No family history of migraines or seizure disorders"],
                "personal": ["Student, irregular sleep hours"],
                "ros": {"respiratory": "Normal", "cardiovascular": "Tachycardia", "gastrointestinal": "Vomiting 4 times today", "neurological": "Photophobia present"},
                "investigations": ["WBC 14,800 / mcL (elevated on rapid blood test)"],
                "vitals": {
                    "bp_value": "110/72 mmHg", "bp_source": "kiosk_device", "bp_timestamp": "Kiosk · 08:32 AM", "bp_is_abnormal": False,
                    "sugar_value": "94 mg/dL", "sugar_source": "kiosk_device", "sugar_timestamp": "Kiosk · 08:32 AM",
                    "blood_group_value": "O+", "blood_group_source": "self_reported",
                    "spo2_value": "99 %", "spo2_source": "kiosk_device", "spo2_timestamp": "Kiosk · 08:32 AM",
                    "pulse_value": "104 bpm", "pulse_source": "kiosk_device", "pulse_timestamp": "Kiosk · 08:32 AM",
                    "temp_value": "102.6 °F", "temp_source": "kiosk_device", "temp_timestamp": "Kiosk · 08:32 AM",
                    "weight_value": "48 kg", "weight_source": "kiosk_device", "weight_timestamp": "Kiosk · 08:32 AM",
                },
                "red_flags": [
                    {"symptom": "Acute high grade fever (39.2°C) with headache and vomiting.", "severity": "Needs attention", "badge_label": "High Fever (39.2°C)", "badge_type": "red"}
                ],
                "ayush": {"prakriti": "Pitta-Vata", "vikriti": "Pitta aggravation", "agni": "Tikshna", "koshtha": "Mrudu"},
                "documents": []
            },
            {
                "token": "A1044",
                "uhid": "UHID998214",
                "abha": "ABHA987123456780",
                "name": "Amit Kumar",
                "age": 56,
                "gender": "Male",
                "phone": "+91 98765 43214",
                "address": "C-12, Kolar Road, Bhopal",
                "attendant": "Self",
                "emergency_name": "Ritu Kumar",
                "emergency_relation": "Wife",
                "emergency_phone": "+91 98765 43215",
                "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
                "queue_num": 3,
                "wait_time": "18 min",
                "arrived_at": "08:56 AM",
                "status": "Reviewed",
                "chief_complaint": "High blood pressure follow-up.",
                "hpi": "Known hypertensive. Ran out of medication 4 days ago. BP at kiosk reads 180/110 mmHg. Complains of mild occipital heaviness.",
                "past": ["Hypertension x 8 years", "Dyslipidemia"],
                "allergy": "NKDA",
                "reaction": "None",
                "current_meds": ["Telmisartan 40 mg OD (defaulted)"],
                "family": ["Father died of CVA at age 64"],
                "personal": ["Smoker (5 pack years)", "Sedentary"],
                "ros": {"respiratory": "Clear", "cardiovascular": "Elevated BP 180/110", "gastrointestinal": "Normal"},
                "investigations": ["Serum Creatinine 1.1 mg/dL (1 month ago)"],
                "vitals": {
                    "bp_value": "180/110 mmHg", "bp_source": "kiosk_device", "bp_timestamp": "Kiosk · 08:56 AM", "bp_is_abnormal": True,
                    "sugar_value": "112 mg/dL", "sugar_source": "kiosk_device", "sugar_timestamp": "Kiosk · 08:56 AM",
                    "blood_group_value": "A+", "blood_group_source": "self_reported",
                    "spo2_value": "96 %", "spo2_source": "kiosk_device", "spo2_timestamp": "Kiosk · 08:56 AM",
                    "pulse_value": "88 bpm", "pulse_source": "kiosk_device", "pulse_timestamp": "Kiosk · 08:56 AM",
                    "temp_value": "98.2 °F", "temp_source": "kiosk_device", "temp_timestamp": "Kiosk · 08:56 AM",
                    "weight_value": "78 kg", "weight_source": "kiosk_device", "weight_timestamp": "Kiosk · 08:56 AM",
                },
                "red_flags": [
                    {"symptom": "Severe hypertension reading: BP 180/110 mmHg.", "severity": "Needs attention", "badge_label": "BP 180/110", "badge_type": "red"}
                ],
                "ayush": {"prakriti": "Pitta-Kapha", "vikriti": "Pitta-Vata prakopa", "agni": "Manda", "koshtha": "Krura"},
                "documents": []
            },
            {
                "token": "A1050",
                "uhid": "UHID889001",
                "abha": "ABHA889900112233",
                "name": "Suresh Yadav",
                "age": 62,
                "gender": "Male",
                "phone": "+91 98765 43216",
                "address": "Sector 4, MP Nagar, Bhopal",
                "attendant": "Son",
                "emergency_name": "Alok Yadav",
                "emergency_relation": "Son",
                "emergency_phone": "+91 98765 43217",
                "photo": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
                "queue_num": 9,
                "wait_time": "1 hr 8 min",
                "arrived_at": "08:06 AM",
                "status": "Reviewed",
                "chief_complaint": "Chest discomfort.",
                "hpi": "Intermittent retrosternal tightness with diabetic autonomic neuropathy. Reports mild exertion-induced heaviness.",
                "past": ["Type 2 Diabetes x 12 years", "Coronary Artery Disease"],
                "allergy": "Aspirin (gastritis)",
                "reaction": "Gastric irritation",
                "current_meds": ["Metformin 500 mg BD", "Clopidogrel 75 mg OD"],
                "family": ["Strong family history of CAD"],
                "personal": ["Non-smoker", "Vegetarian"],
                "ros": {"cardiovascular": "Retrosternal tightness", "others": "No dyspnea at rest"},
                "investigations": ["TMT positive (2025)"],
                "vitals": {
                    "bp_value": "136/84 mmHg", "bp_source": "kiosk_device", "bp_timestamp": "Kiosk · 08:06 AM", "bp_is_abnormal": False,
                    "sugar_value": "164 mg/dL", "sugar_source": "kiosk_device", "sugar_timestamp": "Kiosk · 08:06 AM",
                    "blood_group_value": "AB+", "blood_group_source": "self_reported",
                    "spo2_value": "97 %", "spo2_source": "kiosk_device", "spo2_timestamp": "Kiosk · 08:06 AM",
                    "pulse_value": "76 bpm", "pulse_source": "kiosk_device", "pulse_timestamp": "Kiosk · 08:06 AM",
                    "temp_value": "98.4 °F", "temp_source": "kiosk_device", "temp_timestamp": "Kiosk · 08:06 AM",
                    "weight_value": "72 kg", "weight_source": "kiosk_device", "weight_timestamp": "Kiosk · 08:06 AM",
                },
                "red_flags": [
                    {"symptom": "Diabetic with chest discomfort.", "severity": "Needs attention", "badge_label": "Chest Pain", "badge_type": "red"}
                ],
                "ayush": {"prakriti": "Kapha-Vata", "vikriti": "Kapha vriddhi", "agni": "Manda", "koshtha": "Madhyama"},
                "documents": []
            },
            {
                "token": "A1042",
                "uhid": "UHID781902",
                "abha": "ABHA781902345678",
                "name": "Rahul Sharma",
                "age": 42,
                "gender": "Male",
                "phone": "+91 98765 43218",
                "address": "Indrapuri, Bhopal",
                "attendant": "Self",
                "emergency_name": "Meena Sharma",
                "emergency_relation": "Wife",
                "emergency_phone": "+91 98765 43219",
                "photo": "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
                "queue_num": 1,
                "wait_time": "5 min",
                "arrived_at": "09:09 AM",
                "status": "New",
                "chief_complaint": "Fever and body ache since 2 days.",
                "hpi": "Moderate grade intermittent fever accompanied by generalized myalgia and malaise.",
                "past": ["No chronic illnesses"],
                "allergy": "NKDA",
                "reaction": "None",
                "current_meds": [],
                "family": ["None reported"],
                "personal": ["Non-smoker"],
                "ros": {"respiratory": "Mild coryza", "others": "No rashes"},
                "investigations": [],
                "vitals": {
                    "bp_value": "122/80 mmHg", "bp_source": "kiosk_device", "bp_timestamp": "Kiosk · 09:09 AM", "bp_is_abnormal": False,
                    "sugar_value": "98 mg/dL", "sugar_source": "kiosk_device", "sugar_timestamp": "Kiosk · 09:09 AM",
                    "blood_group_value": "O+", "blood_group_source": "self_reported",
                    "spo2_value": "98 %", "spo2_source": "kiosk_device", "spo2_timestamp": "Kiosk · 09:09 AM",
                    "pulse_value": "82 bpm", "pulse_source": "kiosk_device", "pulse_timestamp": "Kiosk · 09:09 AM",
                    "temp_value": "100.2 °F", "temp_source": "kiosk_device", "temp_timestamp": "Kiosk · 09:09 AM",
                    "weight_value": "70 kg", "weight_source": "kiosk_device", "weight_timestamp": "Kiosk · 09:09 AM",
                },
                "red_flags": [],
                "ayush": {"prakriti": "Pitta-Vata", "vikriti": "Pitta prakopa", "agni": "Visham", "koshtha": "Madhyama"},
                "documents": []
            },
            {
                "token": "A1043",
                "uhid": "UHID672341",
                "abha": "ABHA672341998877",
                "name": "Sunita Patel",
                "age": 28,
                "gender": "Female",
                "phone": "+91 98765 43220",
                "address": "Govindpura, Bhopal",
                "attendant": "Self",
                "emergency_name": "Rakesh Patel",
                "emergency_relation": "Husband",
                "emergency_phone": "+91 98765 43221",
                "photo": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
                "queue_num": 2,
                "wait_time": "12 min",
                "arrived_at": "09:02 AM",
                "status": "New",
                "chief_complaint": "Persistent cough.",
                "hpi": "Dry nocturnal cough since 10 days, worse in cold weather. No hemoptysis, no fever.",
                "past": ["Childhood bronchial asthma"],
                "allergy": "Dust mites",
                "reaction": "Bronchospasm",
                "current_meds": ["Inhaler SOS"],
                "family": ["Mother has asthma"],
                "personal": ["Non-smoker"],
                "ros": {"respiratory": "Expiratory wheeze", "others": "No chest pain"},
                "investigations": [],
                "vitals": {
                    "bp_value": "118/76 mmHg", "bp_source": "kiosk_device", "bp_timestamp": "Kiosk · 09:02 AM", "bp_is_abnormal": False,
                    "sugar_value": "92 mg/dL", "sugar_source": "kiosk_device", "sugar_timestamp": "Kiosk · 09:02 AM",
                    "blood_group_value": "B+", "blood_group_source": "self_reported",
                    "spo2_value": "97 %", "spo2_source": "kiosk_device", "spo2_timestamp": "Kiosk · 09:02 AM",
                    "pulse_value": "78 bpm", "pulse_source": "kiosk_device", "pulse_timestamp": "Kiosk · 09:02 AM",
                    "temp_value": "98.4 °F", "temp_source": "kiosk_device", "temp_timestamp": "Kiosk · 09:02 AM",
                    "weight_value": "54 kg", "weight_source": "kiosk_device", "weight_timestamp": "Kiosk · 09:02 AM",
                },
                "red_flags": [],
                "ayush": {"prakriti": "Vata-Kapha", "vikriti": "Vata-Kapha dushti", "agni": "Manda", "koshtha": "Madhyama"},
                "documents": []
            },
            {
                "token": "A1045",
                "uhid": "UHID445612",
                "abha": "ABHA445612334455",
                "name": "Neha Prasad",
                "age": 34,
                "gender": "Female",
                "phone": "+91 98765 43222",
                "address": "Arera Hills, Bhopal",
                "attendant": "Self",
                "emergency_name": "Vikas Prasad",
                "emergency_relation": "Brother",
                "emergency_phone": "+91 98765 43223",
                "photo": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
                "queue_num": 4,
                "wait_time": "26 min",
                "arrived_at": "08:48 AM",
                "status": "New",
                "chief_complaint": "Stomach pain and nausea.",
                "hpi": "Epigastric burning discomfort exacerbated after spicy meals. Associated with mild nausea.",
                "past": ["GERD x 1 year"],
                "allergy": "NKDA",
                "reaction": "None",
                "current_meds": ["Pantoprazole 40 mg"],
                "family": ["None reported"],
                "personal": ["Tea 4 cups daily"],
                "ros": {"gastrointestinal": "Epigastric tenderness", "others": "No vomiting"},
                "investigations": [],
                "vitals": {
                    "bp_value": "116/74 mmHg", "bp_source": "kiosk_device", "bp_timestamp": "Kiosk · 08:48 AM", "bp_is_abnormal": False,
                    "sugar_value": "104 mg/dL", "sugar_source": "kiosk_device", "sugar_timestamp": "Kiosk · 08:48 AM",
                    "blood_group_value": "A-", "blood_group_source": "self_reported",
                    "spo2_value": "99 %", "spo2_source": "kiosk_device", "spo2_timestamp": "Kiosk · 08:48 AM",
                    "pulse_value": "74 bpm", "pulse_source": "kiosk_device", "pulse_timestamp": "Kiosk · 08:48 AM",
                    "temp_value": "98.6 °F", "temp_source": "kiosk_device", "temp_timestamp": "Kiosk · 08:48 AM",
                    "weight_value": "59 kg", "weight_source": "kiosk_device", "weight_timestamp": "Kiosk · 08:48 AM",
                },
                "red_flags": [],
                "ayush": {"prakriti": "Pitta", "vikriti": "Amlapitta", "agni": "Tikshna", "koshtha": "Mrudu"},
                "documents": []
            },
            {
                "token": "A1046",
                "uhid": "UHID773421",
                "abha": "ABHA773421887766",
                "name": "Vikram Rao",
                "age": 60,
                "gender": "Male",
                "phone": "+91 98765 43224",
                "address": "BHEL Township, Bhopal",
                "attendant": "Self",
                "emergency_name": "Shalini Rao",
                "emergency_relation": "Wife",
                "emergency_phone": "+91 98765 43225",
                "photo": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
                "queue_num": 5,
                "wait_time": "35 min",
                "arrived_at": "08:39 AM",
                "status": "New",
                "chief_complaint": "Breathlessness on exertion.",
                "hpi": "Dyspnea on walking uphill or climbing two flights of stairs. Mild bilateral ankle edema.",
                "past": ["Ischemic Heart Disease"],
                "allergy": "NKDA",
                "reaction": "None",
                "current_meds": ["Atorvastatin 20 mg", "Aspirin 75 mg"],
                "family": ["Father CAD"],
                "personal": ["Ex-smoker"],
                "ros": {"respiratory": "Exertional dyspnea", "cardiovascular": "Mild S3 gallop", "extremities": "Bilateral pedal edema"},
                "investigations": ["2D Echo EF 45% (3 months ago)"],
                "vitals": {
                    "bp_value": "130/82 mmHg", "bp_source": "kiosk_device", "bp_timestamp": "Kiosk · 08:39 AM", "bp_is_abnormal": False,
                    "sugar_value": "128 mg/dL", "sugar_source": "kiosk_device", "sugar_timestamp": "Kiosk · 08:39 AM",
                    "blood_group_value": "O+", "blood_group_source": "self_reported",
                    "spo2_value": "95 %", "spo2_source": "kiosk_device", "spo2_timestamp": "Kiosk · 08:39 AM",
                    "pulse_value": "86 bpm", "pulse_source": "kiosk_device", "pulse_timestamp": "Kiosk · 08:39 AM",
                    "temp_value": "98.2 °F", "temp_source": "kiosk_device", "temp_timestamp": "Kiosk · 08:39 AM",
                    "weight_value": "76 kg", "weight_source": "kiosk_device", "weight_timestamp": "Kiosk · 08:39 AM",
                },
                "red_flags": [],
                "ayush": {"prakriti": "Vata-Kapha", "vikriti": "Hridroga lakshana", "agni": "Madhyama", "koshtha": "Krura"},
                "documents": []
            },
            {
                "token": "A1048",
                "uhid": "UHID667812",
                "abha": "ABHA667812554433",
                "name": "Mohammad Khan",
                "age": 45,
                "gender": "Male",
                "phone": "+91 98765 43226",
                "address": "Old City, Bhopal",
                "attendant": "Self",
                "emergency_name": "Yasmin Khan",
                "emergency_relation": "Wife",
                "emergency_phone": "+91 98765 43227",
                "photo": "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
                "queue_num": 7,
                "wait_time": "48 min",
                "arrived_at": "08:26 AM",
                "status": "New",
                "chief_complaint": "Diabetes review.",
                "hpi": "Routine 3-month glycemic checkup. No polyuria, polydipsia, or blurred vision.",
                "past": ["Type 2 Diabetes x 4 years"],
                "allergy": "NKDA",
                "reaction": "None",
                "current_meds": ["Glimepiride 1 mg OD", "Metformin 500 mg BD"],
                "family": ["Mother Diabetic"],
                "personal": ["Non-smoker"],
                "ros": {"endocrine": "Controlled glycemic state", "others": "No paresthesias"},
                "investigations": ["HbA1c 7.2% (last check)"],
                "vitals": {
                    "bp_value": "128/84 mmHg", "bp_source": "kiosk_device", "bp_timestamp": "Kiosk · 08:26 AM", "bp_is_abnormal": False,
                    "sugar_value": "138 mg/dL", "sugar_source": "kiosk_device", "sugar_timestamp": "Kiosk · 08:26 AM",
                    "blood_group_value": "B+", "blood_group_source": "self_reported",
                    "spo2_value": "98 %", "spo2_source": "kiosk_device", "spo2_timestamp": "Kiosk · 08:26 AM",
                    "pulse_value": "76 bpm", "pulse_source": "kiosk_device", "pulse_timestamp": "Kiosk · 08:26 AM",
                    "temp_value": "98.6 °F", "temp_source": "kiosk_device", "temp_timestamp": "Kiosk · 08:26 AM",
                    "weight_value": "81 kg", "weight_source": "kiosk_device", "weight_timestamp": "Kiosk · 08:26 AM",
                },
                "red_flags": [],
                "ayush": {"prakriti": "Kapha-Pitta", "vikriti": "Prameha", "agni": "Manda", "koshtha": "Madhyama"},
                "documents": []
            },
            {
                "token": "A1049",
                "uhid": "UHID335678",
                "abha": "ABHA335678221100",
                "name": "Lata Gupta",
                "age": 38,
                "gender": "Female",
                "phone": "+91 98765 43228",
                "address": "Chuna Bhatti, Bhopal",
                "attendant": "Self",
                "emergency_name": "Sanjay Gupta",
                "emergency_relation": "Husband",
                "emergency_phone": "+91 98765 43229",
                "photo": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
                "queue_num": 8,
                "wait_time": "55 min",
                "arrived_at": "08:19 AM",
                "status": "New",
                "chief_complaint": "Joint pain.",
                "hpi": "Bilateral knee joint pain on prolonged standing or stairs. Morning stiffness lasting 15 minutes.",
                "past": ["Early Osteoarthritis"],
                "allergy": "Ibuprofen (gastritis)",
                "reaction": "Severe epigastric burning",
                "current_meds": ["Calcium + Vit D3"],
                "family": ["Mother had OA knees"],
                "personal": ["Housewife"],
                "ros": {"musculoskeletal": "Knee crepitus present", "others": "No joint effusion"},
                "investigations": ["X-ray both knees (mild medial joint narrowing)"],
                "vitals": {
                    "bp_value": "120/78 mmHg", "bp_source": "kiosk_device", "bp_timestamp": "Kiosk · 08:19 AM", "bp_is_abnormal": False,
                    "sugar_value": "96 mg/dL", "sugar_source": "kiosk_device", "sugar_timestamp": "Kiosk · 08:19 AM",
                    "blood_group_value": "A+", "blood_group_source": "self_reported",
                    "spo2_value": "98 %", "spo2_source": "kiosk_device", "spo2_timestamp": "Kiosk · 08:19 AM",
                    "pulse_value": "72 bpm", "pulse_source": "kiosk_device", "pulse_timestamp": "Kiosk · 08:19 AM",
                    "temp_value": "98.4 °F", "temp_source": "kiosk_device", "temp_timestamp": "Kiosk · 08:19 AM",
                    "weight_value": "68 kg", "weight_source": "kiosk_device", "weight_timestamp": "Kiosk · 08:19 AM",
                },
                "red_flags": [],
                "ayush": {"prakriti": "Vata-Kapha", "vikriti": "Sandhigata Vata", "agni": "Visham", "koshtha": "Madhyama"},
                "documents": []
            },
            {
                "token": "A1051",
                "uhid": "UHID776543",
                "abha": "ABHA776543110099",
                "name": "Priya Rathi",
                "age": 27,
                "gender": "Female",
                "phone": "+91 98765 43230",
                "address": "Ayodhya Bypass, Bhopal",
                "attendant": "Self",
                "emergency_name": "Deepak Rathi",
                "emergency_relation": "Husband",
                "emergency_phone": "+91 98765 43231",
                "photo": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
                "queue_num": 10,
                "wait_time": "1 hr 15 min",
                "arrived_at": "07:59 AM",
                "status": "New",
                "chief_complaint": "Skin allergy and itching.",
                "hpi": "Pruritic erythematous urticarial wheals across forearms and neck following cosmetic application.",
                "past": ["Contact dermatitis"],
                "allergy": "Benzoyl peroxide",
                "reaction": "Facial erythema",
                "current_meds": ["Cetirizine 10 mg SOS"],
                "family": ["Atopy in brother"],
                "personal": ["Teacher"],
                "ros": {"integumentary": "Erythematous plaques on forearms", "respiratory": "Normal"},
                "investigations": [],
                "vitals": {
                    "bp_value": "114/72 mmHg", "bp_source": "kiosk_device", "bp_timestamp": "Kiosk · 07:59 AM", "bp_is_abnormal": False,
                    "sugar_value": "88 mg/dL", "sugar_source": "kiosk_device", "sugar_timestamp": "Kiosk · 07:59 AM",
                    "blood_group_value": "AB-", "blood_group_source": "self_reported",
                    "spo2_value": "99 %", "spo2_source": "kiosk_device", "spo2_timestamp": "Kiosk · 07:59 AM",
                    "pulse_value": "80 bpm", "pulse_source": "kiosk_device", "pulse_timestamp": "Kiosk · 07:59 AM",
                    "temp_value": "98.4 °F", "temp_source": "kiosk_device", "temp_timestamp": "Kiosk · 07:59 AM",
                    "weight_value": "52 kg", "weight_source": "kiosk_device", "weight_timestamp": "Kiosk · 07:59 AM",
                },
                "red_flags": [],
                "ayush": {"prakriti": "Pitta", "vikriti": "Sheetapitta", "agni": "Tikshna", "koshtha": "Mrudu"},
                "documents": []
            },
            {
                "token": "A1041",
                "uhid": "UHID998123",
                "abha": "ABHA998123001122",
                "name": "Rajesh Verma",
                "age": 52,
                "gender": "Male",
                "phone": "+91 98765 43232",
                "address": "Berasia Road, Bhopal",
                "attendant": "Self",
                "emergency_name": "Kavita Verma",
                "emergency_relation": "Wife",
                "emergency_phone": "+91 98765 43233",
                "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
                "queue_num": 11,
                "wait_time": "1 hr 22 min",
                "arrived_at": "07:52 AM",
                "status": "New",
                "chief_complaint": "Routine checkup and generalized fatigue.",
                "hpi": "General lethargy and daytime somnolence over 3 weeks. No fever, weight loss, or polyuria.",
                "past": ["Mild fatty liver (Grade 1)"],
                "allergy": "NKDA",
                "reaction": "None",
                "current_meds": ["Multivitamin"],
                "family": ["None reported"],
                "personal": ["Desk accountant"],
                "ros": {"general": "Fatigue", "others": "Unremarkable"},
                "investigations": ["USG Abdomen Grade 1 Steatosis"],
                "vitals": {
                    "bp_value": "124/80 mmHg", "bp_source": "kiosk_device", "bp_timestamp": "Kiosk · 07:52 AM", "bp_is_abnormal": False,
                    "sugar_value": "102 mg/dL", "sugar_source": "kiosk_device", "sugar_timestamp": "Kiosk · 07:52 AM",
                    "blood_group_value": "O+", "blood_group_source": "self_reported",
                    "spo2_value": "98 %", "spo2_source": "kiosk_device", "spo2_timestamp": "Kiosk · 07:52 AM",
                    "pulse_value": "74 bpm", "pulse_source": "kiosk_device", "pulse_timestamp": "Kiosk · 07:52 AM",
                    "temp_value": "98.2 °F", "temp_source": "kiosk_device", "temp_timestamp": "Kiosk · 07:52 AM",
                    "weight_value": "75 kg", "weight_source": "kiosk_device", "weight_timestamp": "Kiosk · 07:52 AM",
                },
                "red_flags": [],
                "ayush": {"prakriti": "Kapha-Pitta", "vikriti": "Alasya / Dhatukshaya", "agni": "Manda", "koshtha": "Madhyama"},
                "documents": []
            }
        ]

        # Insert patients and related records
        for pdata in patients_data:
            p = Patient.objects.create(
                uhid=pdata["uhid"],
                abha_id=pdata["abha"],
                queue_token=pdata["token"],
                name=pdata["name"],
                age=pdata["age"],
                gender=pdata["gender"],
                phone=pdata["phone"],
                address=pdata["address"],
                photo_url=pdata["photo"],
                attendant=pdata["attendant"],
                emergency_name=pdata["emergency_name"],
                emergency_relation=pdata["emergency_relation"],
                emergency_phone=pdata["emergency_phone"],
            )

            # QueueItem
            QueueItem.objects.create(
                patient=p,
                status=pdata["status"],
                queue_number=pdata["queue_num"],
                wait_time=pdata["wait_time"],
                arrived_at=pdata["arrived_at"],
                reviewed_at="10:28 AM, 03 Sep 2026" if pdata["status"] == "Reviewed" else None,
            )

            # Vitals
            v = pdata["vitals"]
            Vitals.objects.create(
                patient=p,
                bp_value=v["bp_value"], bp_source=v["bp_source"], bp_timestamp=v["bp_timestamp"], bp_is_abnormal=v["bp_is_abnormal"],
                sugar_value=v["sugar_value"], sugar_source=v["sugar_source"], sugar_timestamp=v["sugar_timestamp"],
                blood_group_value=v["blood_group_value"], blood_group_source=v["blood_group_source"],
                spo2_value=v["spo2_value"], spo2_source=v["spo2_source"], spo2_timestamp=v["spo2_timestamp"],
                pulse_value=v["pulse_value"], pulse_source=v["pulse_source"], pulse_timestamp=v["pulse_timestamp"],
                temp_value=v["temp_value"], temp_source=v["temp_source"], temp_timestamp=v["temp_timestamp"],
                weight_value=v["weight_value"], weight_source=v["weight_source"], weight_timestamp=v["weight_timestamp"],
            )

            # ClinicalSummary
            ay = pdata["ayush"]
            ClinicalSummary.objects.create(
                patient=p,
                chief_complaint=pdata["chief_complaint"],
                history_of_present_illness=pdata["hpi"],
                past_history=pdata["past"],
                allergy_name=pdata["allergy"],
                allergy_reaction=pdata["reaction"],
                current_meds=pdata["current_meds"],
                family_history=pdata["family"],
                personal_history=pdata["personal"],
                review_of_systems=pdata["ros"],
                prior_investigations_summary=pdata["investigations"],
                prakriti=ay["prakriti"],
                vikriti=ay["vikriti"],
                agni=ay["agni"],
                koshtha=ay["koshtha"],
            )

            # Red flags
            for rf in pdata.get("red_flags", []):
                RedFlag.objects.create(
                    patient=p,
                    symptom=rf["symptom"],
                    severity=rf["severity"],
                    badge_label=rf["badge_label"],
                    badge_type=rf["badge_type"],
                    is_active=True if pdata["status"] == "New" else False,
                )

            # Documents
            for doc in pdata.get("documents", []):
                ScannedDocument.objects.create(
                    patient=p,
                    doc_id=doc["doc_id"],
                    doc_type=doc["doc_type"],
                    subtitle=doc.get("subtitle", ""),
                    pages=doc.get("pages", 1),
                    date=doc.get("date", "03 Sep 2026"),
                    time=doc.get("time", "09:08 AM"),
                    file_id=doc.get("file_id", "DOC_12345"),
                    source=doc.get("source", "MediKiosk (Patient Scan)"),
                    impression=doc.get("impression", ""),
                    signatory=doc.get("signatory", ""),
                    preview_url=doc.get("preview_url", ""),
                    pages_list=doc.get("pages_list", []),
                    is_flagged_rescan=False,
                )

        # 6. Seed Sync Action Items
        SyncActionItem.objects.all().delete()
        sync_items = [
            {
                "action_id": "sync-1",
                "patient_token": "A1052",
                "uhid": "UHID778901",
                "action_type": "Patient summary",
                "timestamp": "03 Sep 2026, 11:20 AM",
                "status": "Pending",
                "details": "Pre-consultation draft awaiting final verification by HIS server.",
            },
            {
                "action_id": "sync-2",
                "patient_token": "A1048",
                "uhid": "UHID667320",
                "action_type": "Outcome (Treated)",
                "timestamp": "03 Sep 2026, 10:55 AM",
                "status": "Pending",
                "details": "Prescription details queued for hospital pharmacy dispension.",
            },
            {
                "action_id": "sync-3",
                "patient_token": "A1046",
                "uhid": "UHID556781",
                "action_type": "Outcome (Referred)",
                "timestamp": "03 Sep 2026, 09:42 AM",
                "status": "Synced",
                "details": "Specialist referral dispatched to Cardiology OPD Desk 1.",
            },
            {
                "action_id": "sync-4",
                "patient_token": "A1045",
                "uhid": "UHID334211",
                "action_type": "Patient summary",
                "timestamp": "03 Sep 2026, 09:15 AM",
                "status": "Synced",
                "details": "Confirmed summary written to central EHR archive.",
            },
            {
                "action_id": "sync-5",
                "patient_token": "A1041",
                "uhid": "UHID998123",
                "action_type": "Documents (2 files)",
                "timestamp": "03 Sep 2026, 08:50 AM",
                "status": "Synced",
                "details": "High-resolution sensor scans synced to hospital PACS archive.",
            },
        ]
        for s in sync_items:
            SyncActionItem.objects.create(**s)

        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {len(patients_data)} patients, doctor profile, and settings!"))
