# Generated by Django 5.2.17 on 2026-09-08 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('badge_color', models.CharField(default='bg-emerald-100 text-emerald-800', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='patients.patient')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('Treated & Discharged', 'Treated & Discharged'), ('Referred to Specialist', 'Referred to Specialist'), ('Advised Investigation', 'Advised Investigation'), ('Admitted', 'Admitted'), ('Follow-up', 'Follow-up')], default='Treated & Discharged', max_length=50)),
                ('clinical_notes', models.TextField(blank=True)),
                ('follow_up_date', models.CharField(blank=True, max_length=50)),
                ('remind_sms', models.BooleanField(default=True)),
                ('referred_specialist', models.CharField(blank=True, max_length=150)),
                ('additional_instructions', models.TextField(blank=True)),
                ('advice', models.JSONField(default=list)),
                ('recorded_at', models.CharField(default='11:42 AM, 03 Sep 2026', max_length=100)),
                ('doctor_name', models.CharField(default='Dr. Anjali Verma', max_length=150)),
                ('pushed_to_his', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_outcome', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.CharField(default='1 tablet once daily', max_length=100)),
                ('duration', models.CharField(default='30 days', max_length=100)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultationoutcome')),
            ],
        ),
    ]
