# Generated by Django 5.2.17 on 2026-09-08 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50, unique=True)),
                ('abha_id', models.CharField(blank=True, max_length=50)),
                ('queue_token', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('photo_url', models.TextField(blank=True)),
                ('attendant', models.CharField(default='Self', max_length=50)),
                ('emergency_name', models.CharField(blank=True, max_length=150)),
                ('emergency_relation', models.CharField(blank=True, max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField()),
                ('past_history', models.JSONField(default=list)),
                ('allergy_name', models.CharField(default='NKDA', max_length=150)),
                ('allergy_reaction', models.CharField(default='None', max_length=150)),
                ('current_meds', models.JSONField(default=list)),
                ('family_history', models.JSONField(default=list)),
                ('personal_history', models.JSONField(default=list)),
                ('review_of_systems', models.JSONField(default=dict)),
                ('prior_investigations_summary', models.JSONField(default=list)),
                ('prakriti', models.CharField(default='Vata-Pitta', max_length=100)),
                ('vikriti', models.CharField(default='Vata aggravation', max_length=100)),
                ('agni', models.CharField(default='Madhyama', max_length=100)),
                ('koshtha', models.CharField(default='Madhyama', max_length=100)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_summary', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed')], default='New', max_length=20)),
                ('queue_number', models.IntegerField(default=1)),
                ('wait_time', models.CharField(default='5 min', max_length=50)),
                ('arrived_at', models.CharField(default='09:12 AM', max_length=50)),
                ('reviewed_at', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_item', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.TextField()),
                ('severity', models.CharField(default='Needs attention', max_length=50)),
                ('badge_label', models.CharField(default='Critical', max_length=100)),
                ('badge_type', models.CharField(default='red', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flags', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ScannedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=100)),
                ('doc_type', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=150)),
                ('pages', models.IntegerField(default=1)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('file_id', models.CharField(max_length=100)),
                ('source', models.CharField(default='MediKiosk (Patient Scan)', max_length=150)),
                ('impression', models.TextField(blank=True)),
                ('signatory', models.CharField(blank=True, max_length=200)),
                ('preview_url', models.TextField(blank=True)),
                ('pages_list', models.JSONField(default=list)),
                ('is_flagged_rescan', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='Dr. Anjali Verma', max_length=150)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='patients.scanneddocument')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_value', models.CharField(default='120/80 mmHg', max_length=50)),
                ('bp_source', models.CharField(default='kiosk_device', max_length=50)),
                ('bp_timestamp', models.CharField(default='Kiosk · 09:12 AM', max_length=100)),
                ('bp_is_abnormal', models.BooleanField(default=False)),
                ('sugar_value', models.CharField(default='100 mg/dL', max_length=50)),
                ('sugar_source', models.CharField(default='self_reported', max_length=50)),
                ('sugar_timestamp', models.CharField(default='Self reported · 09:10 AM', max_length=100)),
                ('blood_group_value', models.CharField(default='B+', max_length=10)),
                ('blood_group_source', models.CharField(default='self_reported', max_length=50)),
                ('spo2_value', models.CharField(default='98 %', max_length=50)),
                ('spo2_source', models.CharField(default='kiosk_device', max_length=50)),
                ('spo2_timestamp', models.CharField(default='Kiosk · 09:12 AM', max_length=100)),
                ('pulse_value', models.CharField(default='72 bpm', max_length=50)),
                ('pulse_source', models.CharField(default='kiosk_device', max_length=50)),
                ('pulse_timestamp', models.CharField(default='Kiosk · 09:12 AM', max_length=100)),
                ('temp_value', models.CharField(default='98.6 °F', max_length=50)),
                ('temp_source', models.CharField(default='kiosk_device', max_length=50)),
                ('temp_timestamp', models.CharField(default='Kiosk · 09:12 AM', max_length=100)),
                ('weight_value', models.CharField(default='65 kg', max_length=50)),
                ('weight_source', models.CharField(default='kiosk_device', max_length=50)),
                ('weight_timestamp', models.CharField(default='Kiosk · 09:12 AM', max_length=100)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
            ],
        ),
    ]
