import { PatientRecord, DoctorProfile, SyncAction } from '@/types';

export const mockDoctorProfile: DoctorProfile = {
  hpr_id: 'HPR123456',
  name: 'Dr. Anjali Verma',
  degrees: 'MBBS, MD (Internal Medicine)',
  designation: 'Consultant – General Medicine',
  department: 'General Medicine OPD',
  hospital: 'District Hospital, Bhopal',
  hospital_address: 'E-102, Arera Colony, Bhopal, Madhya Pradesh - 462016',
  counter_desk: 'OPD Desk 4',
  timings: '09:00 AM – 04:00 PM',
  email: 'anjali.verma@bhopalhosp.gov.in',
  phone: '+91 98765 43210',
  is_verified_abdm: true,
  status: 'Active',
};

export const mockInitialPatients: PatientRecord[] = [
  {
    patient: {
      photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      abha_id: 'ABHA832017665432',
      age: 36,
      gender: 'Male',
      queue_token: 'A1052',
      uhid: 'UHID778901',
      name: 'Rohit Mehta',
      phone: '+91 98765 43210',
      address: 'E-102, Arera Colony, Bhopal, Madhya Pradesh - 462016',
      attendant: 'Self',
      emergency_contact: {
        name: 'Neha Mehta',
        relation: 'Spouse',
        phone: '+91 98765 43211',
      },
    },
    status: 'New',
    waitTime: 'Just now',
    queueNumber: 1,
    arrivedAt: '09:12 AM',
    chief_complaint: 'Chest pain since yesterday.',
    history_of_present_illness:
      'Patient reports intermittent left-sided chest pain since yesterday evening. Pain is moderate in intensity, non-radiating, and not associated with exertion. Also reports mild shortness of breath and fatigue. No similar episodes in the past.',
    past_history: [
      'Hypertension (diagnosed 2 years ago)',
      'No history of diabetes',
      'No previous surgeries',
      'No hospitalizations in last 5 years',
    ],
    drug_allergy_history: {
      allergy: 'Penicillin',
      reaction: 'Rash',
      currentMeds: ['Amlodipine 5 mg (OD)'],
    },
    family_history: [
      'Father: Hypertension',
      'Mother: Type 2 Diabetes',
      'No history of heart disease in family',
    ],
    personal_history: [
      'Non-smoker',
      'Occasional alcohol consumption',
      'Sedentary lifestyle (desk job)',
    ],
    review_of_systems: {
      respiratory: 'Mild breathlessness',
      cardiovascular: 'Chest pain',
      gastrointestinal: 'No nausea or vomiting',
      others: 'No significant complaints',
    },
    prior_investigations_summary: [
      'ECG on file (03 Sep 2026) – see attached',
      'Blood Panel available (28 Aug 2026)',
      'No other investigations reported',
    ],
    vitals: {
      blood_pressure: {
        value: '148/92 mmHg',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:12 AM',
        isAbnormal: true,
      },
      blood_sugar: {
        value: '108 mg/dL',
        source: 'self_reported',
        timestamp: 'Self reported · 09:10 AM',
      },
      blood_group: {
        value: 'B+',
        source: 'self_reported',
      },
      spo2: {
        value: '97 %',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:12 AM',
      },
      pulse: {
        value: '84 bpm',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:12 AM',
      },
      temperature: {
        value: '98.4 °F',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:12 AM',
      },
      weight: {
        value: '67 kg',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:12 AM',
      },
    },
    red_flags: [
      {
        symptom: 'Chest pain reported since yesterday. Monitor and assess immediately.',
        severity: 'Needs attention',
        badgeLabel: 'Chest Pain',
        badgeType: 'red',
      },
    ],
    ayush: {
      prakriti: 'Vata-Pitta',
      vikriti: 'Vata aggravation',
      agni: 'Madhyama',
      koshtha: 'Madhyama',
    },
    documents: [
      {
        id: 'ecg-rohit',
        doc_type: 'ECG',
        subtitle: '12-Lead Electrocardiogram',
        pages: 2,
        date: '03 Sep 2026',
        time: '09:08 AM',
        fileId: 'DOC_20260903_090812',
        source: 'MediKiosk (Patient Scan)',
        impression: 'Normal sinus rhythm. No acute ST-T changes seen. Please correlate clinically.',
        signatory: 'Dr. S. Kulkarni MD (Cardiology) Reg. No. MP/23456',
        pagesList: [
          {
            pageNumber: 1,
            title: '12-Lead Rhythm Strip Lead I, II, III, aVR, aVL, aVF',
            imageUrl: '/ecg_p1.svg',
          },
          {
            pageNumber: 2,
            title: 'Precordial Leads V1 - V6 Detailed Analysis',
            imageUrl: '/ecg_p2.svg',
          },
        ],
      },
      {
        id: 'blood-panel-rohit',
        doc_type: 'Blood Panel (Lab Report)',
        subtitle: 'Complete Metabolic Profile & CBC',
        pages: 3,
        date: '28 Aug 2026',
        time: '02:15 PM',
        fileId: 'DOC_20260828_141500',
        source: 'MediKiosk (Patient Scan)',
        impression: 'Mild hyperlipidemia. Normal renal function. Serum Creatinine 0.9 mg/dL.',
        signatory: 'Dr. R. Sharma MD (Pathology)',
        pagesList: [
          { pageNumber: 1, title: 'Complete Blood Count (CBC)', imageUrl: '/lab_p1.svg' },
          { pageNumber: 2, title: 'Kidney Function Test (KFT)', imageUrl: '/lab_p2.svg' },
          { pageNumber: 3, title: 'Lipid Profile', imageUrl: '/lab_p3.svg' },
        ],
      },
      {
        id: 'rx-rohit',
        doc_type: 'Previous Prescription',
        subtitle: 'OPD Consultation Slip',
        pages: 1,
        date: '15 Aug 2026',
        time: '11:20 AM',
        fileId: 'DOC_20260815_112000',
        source: 'MediKiosk (Patient Scan)',
        impression: 'Tab. Amlodipine 5mg OD prescribed for primary hypertension.',
        signatory: 'Dr. M. Joshi MD (General Medicine)',
        pagesList: [
          { pageNumber: 1, title: 'Prescription Slip', imageUrl: '/rx_p1.svg' },
        ],
      },
    ],
  },
  {
    patient: {
      photo_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      abha_id: 'ABHA992011234882',
      age: 19,
      gender: 'Female',
      queue_token: 'A1047',
      uhid: 'UHID221904',
      name: 'Pooja Singh',
      phone: '+91 94250 11223',
      address: 'Near Old Bus Stand, Sehore, MP',
      emergency_contact: {
        name: 'Ramesh Singh',
        relation: 'Father',
        phone: '+91 94250 11220',
      },
    },
    status: 'New',
    waitTime: '42 min',
    queueNumber: 6,
    arrivedAt: '08:32 AM',
    chief_complaint: 'Severe headache and vomiting since 2 days.',
    history_of_present_illness:
      'Sudden onset throbbing headache with high grade fever and nausea. Patient vomited 4 times since morning. Complains of mild neck stiffness and photophobia.',
    past_history: ['No known prior chronic illnesses', 'No previous hospital admissions'],
    drug_allergy_history: {
      allergy: 'Unknown',
      reaction: 'Patient said: I don\'t know',
      currentMeds: ['Paracetamol 650mg taken 4 hours ago'],
    },
    family_history: ['Not asked this session'],
    personal_history: ['Student', 'Non-smoker', 'Adequate sleep till 3 days ago'],
    review_of_systems: {
      respiratory: 'No cough or shortness of breath',
      cardiovascular: 'Sinus tachycardia secondary to pyrexia',
      gastrointestinal: 'Recurrent vomiting, anorexia',
      others: 'Photophobia and neck pain',
    },
    prior_investigations_summary: [
      'Complete Blood Count (CBC) taken today at local clinic',
    ],
    vitals: {
      blood_pressure: {
        value: '110/72 mmHg',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 08:35 AM',
      },
      blood_sugar: {
        value: '96 mg/dL',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 08:35 AM',
      },
      blood_group: {
        value: 'A+',
        source: 'self_reported',
      },
      spo2: {
        value: '99 %',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 08:35 AM',
      },
      pulse: {
        value: '104 bpm',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 08:35 AM',
        isAbnormal: true,
      },
      temperature: {
        value: '102.5 °F (39.2°C)',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 08:35 AM',
        isAbnormal: true,
      },
      weight: {
        value: '48 kg',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 08:35 AM',
      },
    },
    red_flags: [
      {
        symptom: 'High Fever (39.2°C) with persistent headache and vomiting.',
        severity: 'Needs attention',
        badgeLabel: 'High Fever (39.2°C)',
        badgeType: 'red',
      },
      {
        symptom: 'Vomiting and photophobia reported.',
        severity: 'Needs attention',
        badgeLabel: 'Vomiting',
        badgeType: 'gray',
      },
    ],
    ayush: {
      prakriti: 'Pitta-Kapha',
      vikriti: 'Pitta-Vata aggravation',
      agni: 'Tikshnagni',
      koshtha: 'Mrudu',
    },
    documents: [
      {
        id: 'cbc-pooja',
        doc_type: 'CBC Report',
        subtitle: 'Emergency Lab Panel',
        pages: 1,
        date: '03 Sep 2026',
        time: '08:10 AM',
        fileId: 'DOC_20260903_081015',
        source: 'MediKiosk (Patient Scan)',
        impression: 'Leukocytosis (WBC 14,200/mcL with neutrophilia). Platelets normal.',
        signatory: 'Dr. V. Rao MD (Pathology)',
        pagesList: [{ pageNumber: 1, title: 'CBC Slip', imageUrl: '/lab_p1.svg' }],
      },
    ],
  },
  {
    patient: {
      photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      abha_id: 'ABHA118944567890',
      age: 56,
      gender: 'Male',
      queue_token: 'A1044',
      uhid: 'UHID998214',
      name: 'Amit Kumar',
      phone: '+91 98260 55443',
      address: 'Shahpura, Bhopal, MP',
      emergency_contact: {
        name: 'Sunita Kumar',
        relation: 'Spouse',
        phone: '+91 98260 55440',
      },
    },
    status: 'New',
    waitTime: '18 min',
    queueNumber: 3,
    arrivedAt: '08:56 AM',
    chief_complaint: 'High blood pressure follow-up and dizziness.',
    history_of_present_illness:
      'Known hypertensive for 10 years. Reports frequent morning headaches in the occipital region and occasional postural dizziness. Ran out of medications 5 days ago.',
    past_history: [
      'Essential Hypertension (10 years)',
      'Type 2 Diabetes Mellitus (5 years)',
      'No previous myocardial infarction',
    ],
    drug_allergy_history: {
      allergy: 'None',
      reaction: 'NKDA (No Known Drug Allergies)',
      currentMeds: ['Telmisartan 40mg (stopped 5 days ago)', 'Metformin 500mg BD'],
    },
    family_history: ['Father died of cerebrovascular accident (stroke) at age 64', 'Mother had diabetes'],
    personal_history: ['Ex-smoker (quit 8 years ago)', 'Vegetarian diet', 'Moderate stress levels'],
    review_of_systems: {
      cardiovascular: 'Marked hypertension, palpitations on exertion',
      respiratory: 'Normal vesicular breathing',
      gastrointestinal: 'Mild acid reflux',
    },
    prior_investigations_summary: [
      'Previous Discharge Summary (May 2025)',
      'Lipid Profile (July 2026) - Total Cholesterol 220 mg/dL',
    ],
    vitals: {
      blood_pressure: {
        value: '180/110 mmHg',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:00 AM',
        isAbnormal: true,
      },
      blood_sugar: {
        value: '164 mg/dL',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:00 AM',
        isAbnormal: true,
      },
      blood_group: {
        value: 'AB+',
        source: 'self_reported',
      },
      spo2: {
        value: '96 %',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:00 AM',
      },
      pulse: {
        value: '76 bpm',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:00 AM',
      },
      temperature: {
        value: '98.2 °F',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:00 AM',
      },
      weight: {
        value: '82 kg',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:00 AM',
      },
    },
    red_flags: [
      {
        symptom: 'Critically High Blood Pressure (180/110 mmHg). Requires urgent medical evaluation.',
        severity: 'Needs attention',
        badgeLabel: 'BP 180/110',
        badgeType: 'red',
      },
      {
        symptom: 'Known Hypertensive with medication default.',
        severity: 'Needs attention',
        badgeLabel: 'Known Hypertensive',
        badgeType: 'gray',
      },
    ],
    ayush: {
      prakriti: 'Kapha-Pitta',
      vikriti: 'Kapha-Vata Sanga',
      agni: 'Mandagni',
      koshtha: 'Krura',
    },
    documents: [
      {
        id: 'discharge-amit',
        doc_type: 'Discharge Summary',
        subtitle: 'Hypertensive Urgency Admission',
        pages: 2,
        date: '14 May 2025',
        time: '04:30 PM',
        fileId: 'DOC_20250514_163012',
        source: 'MediKiosk (Patient Scan)',
        impression: 'Admitted for accelerated hypertension. Stabilized on Dual Therapy.',
        signatory: 'Dr. K. Saxena MD',
        pagesList: [
          { pageNumber: 1, title: 'Discharge Overview', imageUrl: '/lab_p1.svg' },
          { pageNumber: 2, title: 'Course in Hospital & Rx', imageUrl: '/lab_p2.svg' },
        ],
      },
    ],
  },
  {
    patient: {
      photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      abha_id: 'ABHA332014789552',
      age: 28,
      gender: 'Female',
      queue_token: 'A1043',
      uhid: 'UHID672341',
      name: 'Sunita Patel',
      phone: '+91 97555 43219',
      address: 'Kolar Road, Bhopal, MP',
      emergency_contact: {
        name: 'Deepak Patel',
        relation: 'Brother',
        phone: '+91 97555 43210',
      },
    },
    status: 'New',
    waitTime: '12 min',
    queueNumber: 2,
    arrivedAt: '09:02 AM',
    chief_complaint: 'Persistent dry cough for 10 days.',
    history_of_present_illness:
      'Dry irritating cough without fever or hemoptysis. Worsens at night and in air-conditioned environments. Mild tickling sensation in throat. No relief with OTC cough syrups.',
    past_history: ['Allergic rhinitis during seasonal change'],
    drug_allergy_history: {
      allergy: 'Sulfa Drugs',
      reaction: 'Urticaria / Hives',
      currentMeds: ['Levocetirizine 5mg as needed'],
    },
    family_history: ['Not asked this session'],
    personal_history: ['School teacher', 'Non-smoker', 'No pets at home'],
    review_of_systems: {
      respiratory: 'Dry hacking cough, no wheeze',
      gastrointestinal: 'Normal appetite',
      cardiovascular: 'No complaints',
    },
    prior_investigations_summary: ['Chest X-ray PA View (01 Sep 2026) – Normal lung fields'],
    vitals: {
      blood_pressure: {
        value: '118/76 mmHg',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:05 AM',
      },
      blood_sugar: {
        value: '92 mg/dL',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:05 AM',
      },
      blood_group: {
        value: 'O+',
        source: 'self_reported',
      },
      spo2: {
        value: '99 %',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:05 AM',
      },
      pulse: {
        value: '72 bpm',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:05 AM',
      },
      temperature: {
        value: '98.2 °F',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:05 AM',
      },
      weight: {
        value: '54 kg',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 09:05 AM',
      },
    },
    red_flags: [],
    ayush: {
      prakriti: 'Vata-Kapha',
      vikriti: 'Pranavaha Srotas Kasa',
      agni: 'Sama Agni',
      koshtha: 'Madhyama',
    },
    documents: [
      {
        id: 'cxr-sunita',
        doc_type: 'Chest X-Ray Report',
        subtitle: 'Digital Radiography Report',
        pages: 1,
        date: '01 Sep 2026',
        time: '10:15 AM',
        fileId: 'DOC_20260901_101522',
        source: 'MediKiosk (Patient Scan)',
        impression: 'Both lung fields clear. Bronchovascular markings within normal limits. Cardiac size normal.',
        signatory: 'Dr. P. Tiwari MD (Radiology)',
        pagesList: [{ pageNumber: 1, title: 'CXR PA View', imageUrl: '/rx_p1.svg' }],
      },
    ],
  },
  {
    patient: {
      photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      abha_id: 'ABHA776612349001',
      age: 62,
      gender: 'Male',
      queue_token: 'A1050',
      uhid: 'UHID889001',
      name: 'Suresh Yadav',
      phone: '+91 94251 99887',
      address: 'BHEL Colony, Bhopal, MP',
      emergency_contact: {
        name: 'Gaurav Yadav',
        relation: 'Son',
        phone: '+91 94251 99880',
      },
    },
    status: 'Reviewed',
    waitTime: '1 hr 8 min',
    queueNumber: 9,
    arrivedAt: '08:05 AM',
    reviewedAt: '10:28 AM, 03 Sep 2026',
    chief_complaint: 'Chest discomfort and routine cardiac check.',
    history_of_present_illness:
      'History of CAD status-post PCI in 2021. Doing well on current medical therapy. Reports mild non-cardiac retrosternal heaviness after heavy meals.',
    past_history: [
      'Coronary Artery Disease (CAD) s/p PCI to LAD (2021)',
      'Type 2 Diabetes Mellitus (12 years)',
      'Hyperlipidemia',
    ],
    drug_allergy_history: {
      allergy: 'None',
      reaction: 'NKDA (No Known Drug Allergies)',
      currentMeds: ['Aspirin 75mg OD', 'Atorvastatin 20mg HS', 'Metoprolol Succinate 25mg OD'],
    },
    family_history: ['Brother has ischemic heart disease'],
    personal_history: ['Retired government engineer', 'Walking 3 km daily', 'Low-fat diabetic diet'],
    review_of_systems: {
      cardiovascular: 'No angina on brisk walking, no orthopnea, no ankle swelling',
      gastrointestinal: 'Postprandial bloating',
    },
    prior_investigations_summary: [
      '2D Echocardiography (July 2026): LVEF 55%, mild concentric LVH',
      'HbA1c: 6.8% (Good glycemic control)',
    ],
    vitals: {
      blood_pressure: {
        value: '130/82 mmHg',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 08:10 AM',
      },
      blood_sugar: {
        value: '132 mg/dL',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 08:10 AM',
      },
      blood_group: {
        value: 'O+',
        source: 'self_reported',
      },
      spo2: {
        value: '98 %',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 08:10 AM',
      },
      pulse: {
        value: '68 bpm',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 08:10 AM',
      },
      temperature: {
        value: '98.0 °F',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 08:10 AM',
      },
      weight: {
        value: '71 kg',
        source: 'kiosk_device',
        timestamp: 'Kiosk · 08:10 AM',
      },
    },
    red_flags: [
      {
        symptom: 'Chest discomfort (CAD history)',
        severity: 'Needs attention',
        badgeLabel: 'Chest Pain',
        badgeType: 'red',
      },
      {
        symptom: 'Diabetic history',
        severity: 'Needs attention',
        badgeLabel: 'Diabetic',
        badgeType: 'gray',
      },
    ],
    ayush: {
      prakriti: 'Pitta-Vata',
      vikriti: 'Hridaya Srotas Balya',
      agni: 'Madhyama',
      koshtha: 'Madhyama',
    },
    documents: [
      {
        id: 'echo-suresh',
        doc_type: '2D Echo Report',
        subtitle: 'Color Doppler Study',
        pages: 2,
        date: '10 Jul 2026',
        time: '11:00 AM',
        fileId: 'DOC_20260710_110022',
        source: 'MediKiosk (Patient Scan)',
        impression: 'Normal LV systolic function (LVEF 55%). Grade 1 LV diastolic dysfunction.',
        signatory: 'Dr. A. Sen MD (Cardiology)',
        pagesList: [
          { pageNumber: 1, title: 'Echo Parameters', imageUrl: '/lab_p1.svg' },
          { pageNumber: 2, title: 'Doppler Curves', imageUrl: '/lab_p2.svg' },
        ],
      },
    ],
    consultation_outcome: {
      outcome_type: 'Treated & Discharged',
      clinical_notes:
        'Patient evaluated for chest discomfort. Non-cardiac etiology confirmed. Vitals completely stable. Continue current CAD regimen without modification. Advised antacid for reflux.',
      prescriptions: [
        {
          id: 'rx-s1',
          name: 'Pantoprazole 40 mg',
          dosage: '1 tablet once daily before breakfast',
          duration: '14 days',
        },
        {
          id: 'rx-s2',
          name: 'Continue existing cardiac medications (Metoprolol, Atorvastatin, Aspirin)',
          dosage: 'As previously prescribed',
          duration: '3 months',
        },
      ],
      advice: ['Low salt, low oil diet', '30 minutes brisk walking daily', 'Avoid heavy dinner'],
      follow_up_date: '03 Oct 2026',
      remind_sms: true,
      recorded_at: '10:32 AM, 03 Sep 2026',
      doctor_name: 'Dr. Anjali Verma',
      pushed_to_his: true,
    },
  },
  // Additional Queue Patients matching 2A.png
  {
    patient: {
      photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      abha_id: 'ABHA554411223399',
      age: 42,
      gender: 'Male',
      queue_token: 'A1042',
      uhid: 'UHID781902',
      name: 'Rahul Sharma',
      phone: '+91 98111 22334',
      emergency_contact: { name: 'Pooja Sharma', relation: 'Spouse', phone: '+91 98111 22330' },
    },
    status: 'New',
    waitTime: '5 min',
    queueNumber: 1,
    arrivedAt: '09:09 AM',
    chief_complaint: 'Fever and body ache since 2 days',
    history_of_present_illness: 'Low grade fever accompanied by generalized myalgia and malaise.',
    past_history: ['No significant past illness'],
    drug_allergy_history: { allergy: 'None', reaction: 'NKDA' },
    family_history: ['Nil'],
    personal_history: ['Desk job'],
    review_of_systems: { others: 'Generalized body ache' },
    prior_investigations_summary: ['None'],
    vitals: {
      blood_pressure: { value: '122/80 mmHg', source: 'kiosk_device', timestamp: 'Kiosk · 09:10 AM' },
      blood_sugar: { value: '102 mg/dL', source: 'kiosk_device', timestamp: 'Kiosk · 09:10 AM' },
      blood_group: { value: 'B+', source: 'self_reported' },
      spo2: { value: '98 %', source: 'kiosk_device', timestamp: 'Kiosk · 09:10 AM' },
      pulse: { value: '78 bpm', source: 'kiosk_device', timestamp: 'Kiosk · 09:10 AM' },
      temperature: { value: '99.2 °F', source: 'kiosk_device', timestamp: 'Kiosk · 09:10 AM' },
      weight: { value: '70 kg', source: 'kiosk_device', timestamp: 'Kiosk · 09:10 AM' },
    },
    red_flags: [],
    ayush: { prakriti: 'Vata-Kapha', vikriti: 'Jwara Sama', agni: 'Mandagni', koshtha: 'Madhyama' },
    documents: [],
  },
  {
    patient: {
      photo_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      abha_id: 'ABHA887766554411',
      age: 34,
      gender: 'Female',
      queue_token: 'A1045',
      uhid: 'UHID445612',
      name: 'Neha Prasad',
      phone: '+91 97111 88776',
      emergency_contact: { name: 'Alok Prasad', relation: 'Husband', phone: '+91 97111 88770' },
    },
    status: 'New',
    waitTime: '26 min',
    queueNumber: 4,
    arrivedAt: '08:48 AM',
    chief_complaint: 'Stomach pain and nausea',
    history_of_present_illness: 'Crampy epigastric pain following meals. Associated with mild nausea.',
    past_history: ['GERD'],
    drug_allergy_history: { allergy: 'None', reaction: 'NKDA' },
    family_history: ['Mother had gallstones'],
    personal_history: ['Tea drinker (4 cups/day)'],
    review_of_systems: { gastrointestinal: 'Epigastric tenderness' },
    prior_investigations_summary: ['USG Abdomen (2024) - Normal'],
    vitals: {
      blood_pressure: { value: '116/74 mmHg', source: 'kiosk_device', timestamp: 'Kiosk · 08:50 AM' },
      blood_sugar: { value: '98 mg/dL', source: 'kiosk_device', timestamp: 'Kiosk · 08:50 AM' },
      blood_group: { value: 'A+', source: 'self_reported' },
      spo2: { value: '99 %', source: 'kiosk_device', timestamp: 'Kiosk · 08:50 AM' },
      pulse: { value: '74 bpm', source: 'kiosk_device', timestamp: 'Kiosk · 08:50 AM' },
      temperature: { value: '98.4 °F', source: 'kiosk_device', timestamp: 'Kiosk · 08:50 AM' },
      weight: { value: '58 kg', source: 'kiosk_device', timestamp: 'Kiosk · 08:50 AM' },
    },
    red_flags: [],
    ayush: { prakriti: 'Pitta-Prakriti', vikriti: 'Amlapitta', agni: 'Tikshnagni', koshtha: 'Mrudu' },
    documents: [],
  },
  {
    patient: {
      photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      abha_id: 'ABHA443322118877',
      age: 60,
      gender: 'Male',
      queue_token: 'A1046',
      uhid: 'UHID773421',
      name: 'Vikram Rao',
      phone: '+91 98930 12345',
      emergency_contact: { name: 'Shobha Rao', relation: 'Spouse', phone: '+91 98930 12340' },
    },
    status: 'New',
    waitTime: '35 min',
    queueNumber: 5,
    arrivedAt: '08:39 AM',
    chief_complaint: 'Breathlessness on exertion',
    history_of_present_illness: 'Grade 2 dyspnea when climbing stairs. Known COPD on inhaler therapy.',
    past_history: ['COPD (5 years)', 'Chronic bronchitis'],
    drug_allergy_history: { allergy: 'None', reaction: 'NKDA', currentMeds: ['Formoterol + Budesonide inhaler'] },
    family_history: ['Father had asthma'],
    personal_history: ['Smoker for 30 years (10 pack-years)'],
    review_of_systems: { respiratory: 'Exertional wheeze' },
    prior_investigations_summary: ['Spirometry (2025): FEV1/FVC 62%'],
    vitals: {
      blood_pressure: { value: '138/84 mmHg', source: 'kiosk_device', timestamp: 'Kiosk · 08:42 AM' },
      blood_sugar: { value: '110 mg/dL', source: 'kiosk_device', timestamp: 'Kiosk · 08:42 AM' },
      blood_group: { value: 'B+', source: 'self_reported' },
      spo2: { value: '94 %', source: 'kiosk_device', timestamp: 'Kiosk · 08:42 AM' },
      pulse: { value: '82 bpm', source: 'kiosk_device', timestamp: 'Kiosk · 08:42 AM' },
      temperature: { value: '98.1 °F', source: 'kiosk_device', timestamp: 'Kiosk · 08:42 AM' },
      weight: { value: '64 kg', source: 'kiosk_device', timestamp: 'Kiosk · 08:42 AM' },
    },
    red_flags: [],
    ayush: { prakriti: 'Vata-Kapha', vikriti: 'Shwasa Roga', agni: 'Madhyama', koshtha: 'Krura' },
    documents: [],
  },
  {
    patient: {
      photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      abha_id: 'ABHA665544332211',
      age: 45,
      gender: 'Male',
      queue_token: 'A1048',
      uhid: 'UHID667812',
      name: 'Mohammad Khan',
      phone: '+91 98270 44556',
      emergency_contact: { name: 'Farida Khan', relation: 'Spouse', phone: '+91 98270 44550' },
    },
    status: 'New',
    waitTime: '48 min',
    queueNumber: 7,
    arrivedAt: '08:26 AM',
    chief_complaint: 'Diabetes review',
    history_of_present_illness: 'Routine 3-month glycemic checkup. Fasting blood sugar on glucometer 142 mg/dL.',
    past_history: ['Type 2 Diabetes (7 years)'],
    drug_allergy_history: { allergy: 'None', reaction: 'NKDA', currentMeds: ['Glimepiride 1mg OD', 'Metformin 500mg BD'] },
    family_history: ['Both parents diabetic'],
    personal_history: ['Businessman, sedentary'],
    review_of_systems: { others: 'Mild polydipsia' },
    prior_investigations_summary: ['HbA1c test slip (Last: 7.4%)'],
    vitals: {
      blood_pressure: { value: '128/82 mmHg', source: 'kiosk_device', timestamp: 'Kiosk · 08:30 AM' },
      blood_sugar: { value: '142 mg/dL', source: 'kiosk_device', timestamp: 'Kiosk · 08:30 AM' },
      blood_group: { value: 'A+', source: 'self_reported' },
      spo2: { value: '98 %', source: 'kiosk_device', timestamp: 'Kiosk · 08:30 AM' },
      pulse: { value: '75 bpm', source: 'kiosk_device', timestamp: 'Kiosk · 08:30 AM' },
      temperature: { value: '98.6 °F', source: 'kiosk_device', timestamp: 'Kiosk · 08:30 AM' },
      weight: { value: '76 kg', source: 'kiosk_device', timestamp: 'Kiosk · 08:30 AM' },
    },
    red_flags: [],
    ayush: { prakriti: 'Kapha-Pitta', vikriti: 'Prameha', agni: 'Mandagni', koshtha: 'Madhyama' },
    documents: [],
  },
  {
    patient: {
      photo_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      abha_id: 'ABHA332211998877',
      age: 38,
      gender: 'Female',
      queue_token: 'A1049',
      uhid: 'UHID335678',
      name: 'Lata Gupta',
      phone: '+91 98263 77889',
      emergency_contact: { name: 'Manoj Gupta', relation: 'Husband', phone: '+91 98263 77880' },
    },
    status: 'New',
    waitTime: '55 min',
    queueNumber: 8,
    arrivedAt: '08:19 AM',
    chief_complaint: 'Joint pain in bilateral knees',
    history_of_present_illness: 'Crepitus and pain in both knees while climbing stairs or squatting. Present for 6 months.',
    past_history: ['Osteopenia'],
    drug_allergy_history: { allergy: 'Ibuprofen', reaction: 'Gastric irritation' },
    family_history: ['Mother had early osteoarthritis'],
    personal_history: ['Homemaker'],
    review_of_systems: { others: 'Bilateral knee crepitus' },
    prior_investigations_summary: ['X-ray Bilateral Knees (Jan 2026) - Mild joint space narrowing'],
    vitals: {
      blood_pressure: { value: '124/80 mmHg', source: 'kiosk_device', timestamp: 'Kiosk · 08:22 AM' },
      blood_sugar: { value: '104 mg/dL', source: 'kiosk_device', timestamp: 'Kiosk · 08:22 AM' },
      blood_group: { value: 'O+', source: 'self_reported' },
      spo2: { value: '99 %', source: 'kiosk_device', timestamp: 'Kiosk · 08:22 AM' },
      pulse: { value: '76 bpm', source: 'kiosk_device', timestamp: 'Kiosk · 08:22 AM' },
      temperature: { value: '98.3 °F', source: 'kiosk_device', timestamp: 'Kiosk · 08:22 AM' },
      weight: { value: '68 kg', source: 'kiosk_device', timestamp: 'Kiosk · 08:22 AM' },
    },
    red_flags: [],
    ayush: { prakriti: 'Vata-Pitta', vikriti: 'Sandhigata Vata', agni: 'Madhyama', koshtha: 'Madhyama' },
    documents: [],
  },
  {
    patient: {
      photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      abha_id: 'ABHA112233445566',
      age: 27,
      gender: 'Female',
      queue_token: 'A1051',
      uhid: 'UHID776543',
      name: 'Priya Rathi',
      phone: '+91 97551 23456',
      emergency_contact: { name: 'Kiran Rathi', relation: 'Mother', phone: '+91 97551 23450' },
    },
    status: 'New',
    waitTime: '1 hr 15 min',
    queueNumber: 10,
    arrivedAt: '07:59 AM',
    chief_complaint: 'Skin allergy and itching',
    history_of_present_illness: 'Erythematous pruritic patches on flexor aspects of forearms for 4 days.',
    past_history: ['Atopic dermatitis in childhood'],
    drug_allergy_history: { allergy: 'None', reaction: 'NKDA' },
    family_history: ['Sibling has asthma'],
    personal_history: ['Software engineer'],
    review_of_systems: { others: 'Cutaneous pruritus' },
    prior_investigations_summary: ['None'],
    vitals: {
      blood_pressure: { value: '112/70 mmHg', source: 'kiosk_device', timestamp: 'Kiosk · 08:02 AM' },
      blood_sugar: { value: '88 mg/dL', source: 'kiosk_device', timestamp: 'Kiosk · 08:02 AM' },
      blood_group: { value: 'AB-', source: 'self_reported' },
      spo2: { value: '100 %', source: 'kiosk_device', timestamp: 'Kiosk · 08:02 AM' },
      pulse: { value: '70 bpm', source: 'kiosk_device', timestamp: 'Kiosk · 08:02 AM' },
      temperature: { value: '98.4 °F', source: 'kiosk_device', timestamp: 'Kiosk · 08:02 AM' },
      weight: { value: '52 kg', source: 'kiosk_device', timestamp: 'Kiosk · 08:02 AM' },
    },
    red_flags: [],
    ayush: { prakriti: 'Pitta-Kapha', vikriti: 'Kushtha / Twak Rog', agni: 'Tikshnagni', koshtha: 'Mrudu' },
    documents: [],
  },
  {
    patient: {
      photo_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      abha_id: 'ABHA778899001122',
      age: 31,
      gender: 'Female',
      queue_token: 'A1041',
      uhid: 'UHID998123',
      name: 'Ananya Sen',
      phone: '+91 98260 11992',
      emergency_contact: { name: 'Subhash Sen', relation: 'Husband', phone: '+91 98260 11990' },
    },
    status: 'Reviewed',
    waitTime: '1 hr 20 min',
    queueNumber: 11,
    arrivedAt: '07:54 AM',
    reviewedAt: '08:50 AM, 03 Sep 2026',
    chief_complaint: 'Thyroid function review',
    history_of_present_illness: 'Known primary hypothyroidism on Thyroxine 50mcg. Routine 6-month TSH evaluation.',
    past_history: ['Hypothyroidism (3 years)'],
    drug_allergy_history: { allergy: 'None', reaction: 'NKDA', currentMeds: ['Levothyroxine 50 mcg OD'] },
    family_history: ['Mother hypothyroid'],
    personal_history: ['Teacher'],
    review_of_systems: { others: 'Occasional morning fatigue' },
    prior_investigations_summary: ['TSH Lab Report (28 Aug 2026): TSH 2.8 mIU/L (Euthyroid)'],
    vitals: {
      blood_pressure: { value: '118/76 mmHg', source: 'kiosk_device', timestamp: 'Kiosk · 07:58 AM' },
      blood_sugar: { value: '94 mg/dL', source: 'kiosk_device', timestamp: 'Kiosk · 07:58 AM' },
      blood_group: { value: 'B+', source: 'self_reported' },
      spo2: { value: '99 %', source: 'kiosk_device', timestamp: 'Kiosk · 07:58 AM' },
      pulse: { value: '72 bpm', source: 'kiosk_device', timestamp: 'Kiosk · 07:58 AM' },
      temperature: { value: '98.2 °F', source: 'kiosk_device', timestamp: 'Kiosk · 07:58 AM' },
      weight: { value: '62 kg', source: 'kiosk_device', timestamp: 'Kiosk · 07:58 AM' },
    },
    red_flags: [],
    ayush: { prakriti: 'Kapha-Vata', vikriti: 'Galaganda Shamana', agni: 'Mandagni', koshtha: 'Madhyama' },
    documents: [],
    consultation_outcome: {
      outcome_type: 'Treated & Discharged',
      clinical_notes: 'TSH is 2.8 mIU/L (optimal range). Continue current Levothyroxine 50mcg. Repeat TSH after 6 months.',
      prescriptions: [{ id: 'rx-a1', name: 'Thyroxine 50 mcg', dosage: '1 tab OD morning empty stomach', duration: '6 months' }],
      advice: ['Take on an empty stomach with plain water at least 30 mins before tea/breakfast'],
      follow_up_date: '03 Mar 2027',
      remind_sms: true,
      recorded_at: '08:52 AM, 03 Sep 2026',
      doctor_name: 'Dr. Anjali Verma',
      pushed_to_his: true,
    },
  },
];

export const mockInitialSyncActions: SyncAction[] = [
  {
    id: 'sync-1',
    patient_token: 'A1052',
    uhid: 'UHID778901',
    patient_name: 'Rohit Mehta',
    action_type: 'Patient summary',
    timestamp: '03 Sep 2026, 11:20 AM',
    status: 'Pending',
  },
  {
    id: 'sync-2',
    patient_token: 'A1048',
    uhid: 'UHID667320',
    patient_name: 'Mohammad Khan',
    action_type: 'Outcome (Treated)',
    timestamp: '03 Sep 2026, 10:55 AM',
    status: 'Pending',
  },
  {
    id: 'sync-3',
    patient_token: 'A1046',
    uhid: 'UHID556781',
    patient_name: 'Vikram Rao',
    action_type: 'Outcome (Referred)',
    timestamp: '03 Sep 2026, 09:42 AM',
    status: 'Synced',
  },
  {
    id: 'sync-4',
    patient_token: 'A1045',
    uhid: 'UHID334211',
    patient_name: 'Neha Prasad',
    action_type: 'Patient summary',
    timestamp: '03 Sep 2026, 09:15 AM',
    status: 'Synced',
  },
  {
    id: 'sync-5',
    patient_token: 'A1041',
    uhid: 'UHID998123',
    patient_name: 'Ananya Sen',
    action_type: 'Documents (2 files)',
    timestamp: '03 Sep 2026, 08:50 AM',
    status: 'Synced',
  },
];
