# Generated by Django 5.2.17 on 2026-09-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpr_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('degrees', models.CharField(default='MBBS, MD (Internal Medicine)', max_length=150)),
                ('designation', models.CharField(default='Consultant – General Medicine', max_length=150)),
                ('department', models.CharField(default='General Medicine OPD', max_length=150)),
                ('hospital', models.CharField(default='District Hospital, Bhopal', max_length=200)),
                ('hospital_address', models.TextField(default='E-102, Arera Colony, Bhopal, Madhya Pradesh - 462016')),
                ('counter_desk', models.CharField(default='Desk 4', max_length=50)),
                ('timings', models.CharField(default='09:00 AM – 04:00 PM', max_length=100)),
                ('email', models.CharField(default='anjali.verma@bhopalhosp.gov.in', max_length=150)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('is_verified_abdm', models.BooleanField(default=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150)),
                ('desk', models.CharField(max_length=50)),
                ('hospital', models.CharField(default='District Hospital, Bhopal', max_length=200)),
                ('timings', models.CharField(default='09:00 AM – 04:00 PM', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
